"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class PaginationMetaTypedDict(TypedDict):
    has_more: NotRequired[bool]
    after_cursor: NotRequired[str]
    before_cursor: NotRequired[str]


class PaginationMeta(BaseModel):
    has_more: Optional[bool] = None

    after_cursor: Optional[str] = None

    before_cursor: Optional[str] = None
