"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TicketSortBy(str, Enum):
    ID = "id"
    SUBJECT = "subject"
    DELETED_AT = "deleted_at"
