
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-12T22:56:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d0d888cd6ec35897cd1c03c972c18d95d27a09b",
 "version": "2.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
