
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-13T14:45:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec03b6b910460d6150d10ce9316f9cc97d021990",
 "version": "2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
