# coding: utf-8

"""
    osparc.io public API

    osparc-simcore public API specifications

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RunningState(str, Enum):
    """
    State of execution of a project's computational workflow  SEE StateType for task state
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    PUBLISHED = 'PUBLISHED'
    NOT_STARTED = 'NOT_STARTED'
    PENDING = 'PENDING'
    WAITING_FOR_RESOURCES = 'WAITING_FOR_RESOURCES'
    STARTED = 'STARTED'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    ABORTED = 'ABORTED'
    WAITING_FOR_CLUSTER = 'WAITING_FOR_CLUSTER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RunningState from a JSON string"""
        return cls(json.loads(json_str))


