# Generated by Django 3.2.4 on 2022-03-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210704_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.city'),
        ),
    ]
