# Generated by Django 3.2.4 on 2022-03-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_genre_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='parent_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.city'),
        ),
    ]
