# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from utils.config_utils import get_default_zenoh_config_file
from utils.key_utils import resolve_key_name

__all__ = ['resolve_key_name']
def get_default_config_path() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import cryptography
import cryptography.x509
import cryptography.x509.oid
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.asymmetric
import cryptography.x509.base
import datetime
import pathlib
import pathlib.Path
import typing
import secrets
import base64
import cryptography.hazmat.primitives.kdf
import cryptography.hazmat.primitives.kdf.pbkdf2
import getpass
import typer
import shutil
import zipfile
import tempfile
import time
import zenoh
import signal
import subprocess
import socket
import loguru
import uuid
import hashlib
import platform
import json
import enum
import tomllib
import importlib
import importlib.metadata
import _frozen_importlib_external
import google
import google.protobuf
import google.protobuf.internal
import rich
import rich.console
import rich.table
import random
import string
import wonderwords
import sys
import select
import re
import paramiko
import cryptography.fernet
import contextlib
import io
import threading