
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-13T15:13:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a249ec2264a82fd26ec988a8a48a0082ba67ed49",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
