"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zendesk.types import BaseModel
from zendesk.utils import FieldMetadata, QueryParamMetadata


class TicketsUpdateManyRequestTypedDict(TypedDict):
    ids: NotRequired[str]
    r"""Comma-separated list of ticket ids"""


class TicketsUpdateManyRequest(BaseModel):
    ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of ticket ids"""
