

class BurstInterfaceC:
    def __init__(self) -> None: ...

    def decode(self, data: bytes, fail_on_crc_error: bool = False) -> list: ...

    def encode(self, packets: list) -> bytes: ...

    @property
    def bytes_handled(self) -> int: ...

    @property
    def bytes_processed(self) -> int: ...

    @property
    def packets_processed(self) -> int: ...

    @property
    def crc_errors(self) -> int: ...

    @property
    def overflow_errors(self) -> int: ...

    @property
    def decode_errors(self) -> int: ...
