APC_KEY_25_LAYOUT = [
    [
        0x20,
        0x21,
        0x22,
        0x23,
        0x24,
        0x25,
        0x26,
        0x27,
    ],
    [
        0x18,
        0x19,
        0x1A,
        0x1B,
        0x1C,
        0x1D,
        0x1E,
        0x1F,
    ],
    [
        0x10,
        0x11,
        0x12,
        0x13,
        0x14,
        0x15,
        0x16,
        0x17,
    ],
    [
        0x08,
        0x09,
        0x0A,
        0x0B,
        0x0C,
        0x0D,
        0x0E,
        0x0F,
    ],
    [
        0x00,
        0x01,
        0x02,
        0x03,
        0x04,
        0x05,
        0x06,
        0x07,
    ],
]

APC_KEY_25_LAYOUT_FLATTENED = [item for row in APC_KEY_25_LAYOUT for item in row]

NUMBER_FONT = {
    "0": [
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
    ],
    "1": [
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
    ],
    "2": [
        [True, True, True],
        [False, False, True],
        [True, True, True],
        [True, False, False],
        [True, True, True],
    ],
    "3": [
        [True, True, True],
        [False, False, True],
        [True, True, True],
        [False, False, True],
        [True, True, True],
    ],
    "4": [
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [False, False, True],
        [False, False, True],
    ],
    "5": [
        [True, True, True],
        [True, False, False],
        [True, True, True],
        [False, False, True],
        [True, True, True],
    ],
    "6": [
        [True, False, False],
        [True, False, False],
        [True, True, True],
        [True, False, True],
        [True, True, True],
    ],
    "7": [
        [True, True, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
        [False, False, True],
    ],
    "8": [
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, True, True],
    ],
    "9": [
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [False, False, True],
        [False, False, True],
    ],
}
TEXT_FONT = {
    "A": [
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
    ],
    "B": [
        [True, True, True],
        [True, False, True],
        [True, True, False],
        [True, False, True],
        [True, True, True],
    ],
    "C": [
        [True, True, True],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, True, True],
    ],
    "D": [
        [True, True, False],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, False],
    ],
    "E": [
        [True, True, True],
        [True, False, False],
        [True, True, True],
        [True, False, False],
        [True, True, True],
    ],
    "F": [
        [True, True, True],
        [True, False, False],
        [True, True, True],
        [True, False, False],
        [True, False, False],
    ],
    "G": [
        [True, True, True],
        [True, False, False],
        [True, False, True],
        [True, False, True],
        [True, True, True],
    ],
    "H": [
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
    ],
    "I": [
        [True, True, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [True, True, True],
    ],
    "J": [
        [True, True, True],
        [False, False, True],
        [False, False, True],
        [True, False, True],
        [True, True, True],
    ],
    "K": [
        [True, False, True],
        [True, False, True],
        [True, True, False],
        [True, False, True],
        [True, False, True],
    ],
    "L": [
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, False, False],
        [True, True, True],
    ],
    "M": [
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
    ],
    "N": [
        [False, False, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
        [True, False, False],
    ],
    "O": [
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
    ],
    "P": [
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [True, False, False],
        [True, False, False],
    ],
    "Q": [
        [True, True, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [False, False, True],
    ],
    "R": [
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [True, True, False],
        [True, False, True],
    ],
    "S": [
        [True, True, True],
        [True, False, False],
        [True, True, True],
        [False, False, True],
        [True, True, True],
    ],
    "T": [
        [True, True, True],
        [False, True, False],
        [False, True, False],
        [False, True, False],
        [False, True, False],
    ],
    "U": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
    ],
    "V": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [False, True, False],
    ],
    "W": [
        [True, False, True],
        [True, False, True],
        [True, False, True],
        [True, True, True],
        [True, False, True],
    ],
    "X": [
        [True, False, True],
        [True, False, True],
        [False, True, False],
        [True, False, True],
        [True, False, True],
    ],
    "Y": [
        [True, False, True],
        [True, False, True],
        [False, True, False],
        [False, False, True],
        [False, False, True],
    ],
    "Z": [
        [True, True, True],
        [False, False, True],
        [False, True, False],
        [True, False, False],
        [True, True, True],
    ],
    " ": [
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
    ],
}
FONT = {**NUMBER_FONT, **TEXT_FONT}
