from camera_ui_python_types.hybrid_observer import HybridObservable as HybridObservable

async def test_asubscribe_endless_operation() -> None: ...
async def test_asubscribe_self_completing_operation() -> None: ...
async def test_asubscribe_error_handling() -> None: ...
