
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-09T18:23:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ac77fa5b958b583b3f7aa6af49f558aac37eb56",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
