# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.get_route_logs_by_route200_response_inner import (
    GetRouteLogsByRoute200ResponseInner,
)


class TestGetRouteLogsByRoute200ResponseInner(unittest.TestCase):
    """GetRouteLogsByRoute200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRouteLogsByRoute200ResponseInner:
        """Test GetRouteLogsByRoute200ResponseInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetRouteLogsByRoute200ResponseInner`
        """
        model = GetRouteLogsByRoute200ResponseInner()
        if include_optional:
            return GetRouteLogsByRoute200ResponseInner(
                var_date = '',
                route_uid = '',
                event_uid = '',
                attn = True,
                status = '',
                text = '',
                url = ''
            )
        else:
            return GetRouteLogsByRoute200ResponseInner(
        )
        """

    def testGetRouteLogsByRoute200ResponseInner(self):
        """Test GetRouteLogsByRoute200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
