
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-12T23:23:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1eb9a5d1fc2cf4c7c3209f568ac48a96313490f5",
 "version": "2.9.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
