
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-10T15:51:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e5fb8d2225567b0f5755e50f9414dca9799c215",
 "version": "1.1.0a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
