# generated by datamodel-codegen:
#   filename:  core/reusable/energy_accuracy_levels.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class AccuracyLevel(Enum):
    standard = "standard"
    low = "low"
    high = "high"


class Unit(Enum):
    Ry = "Ry"


class ReusableSchemaForAccuracyLevelsWithValueAndEnergyUnit(BaseModel):
    accuracy_level: AccuracyLevel
    """
    Parameter value suitable for a specific accuracy level.
    """
    unit: Unit
    """
    Unit of the energy value corresponding to a accuracy_level. The values are expressed in Ry.
    """
    value: float
