export enum AnalyticsEnum {
  // User Activity
  JUPYTER_USER_LOGIN = 'JUPYTER_USER_LOGIN',
  JUPYTER_USER_LOGOUT = 'JUPYTER_USER_LOGOUT',
  JUPYTER_USER_ONBOARDED = 'JUPYTER_USER_ONBOARDED',
  JUPYTER_ACTIVE = 'JUPYTER_ACTIVE', // Like heartbeat but only when view is active
  JUPYTER_HEARTBEAT = 'JUPYTER_HEARTBEAT',
  JUPYTER_POS = 'JUPYTER_POS', // Rerun status logic
  JUPYTER_UNINSTALL = 'JUPYTER_UNINSTALL',

  // Actions
  JUPYTER_USER_SAVE = 'JUPYTER_USER_SAVE',
  JUPYTER_SAVE_SUCCESS = 'JUPYTER_SAVE_SUCCESS',
  JUPYTER_SAVE_FAILURE = 'JUPYTER_SAVE_FAILURE',
  JUPYTER_SAVE_SELECTION = 'JUPYTER_SAVE_SELECTION',
  JUPYTER_SAVE_ACTIVE_CELL = 'JUPYTER_SAVE_ACTIVE_CELL',
  JUPYTER_SAVE_ACTIVE_CELL_BUTTON = 'JUPYTER_SAVE_ACTIVE_CELL_BUTTON',

  JUPYTER_DELETE = 'JUPYTER_DELETE',
  JUPYTER_DELETE_SUCCESS = 'JUPYTER_DELETE_SUCCESS',
  JUPYTER_DELETE_FAILURE = 'JUPYTER_DELETE_FAILURE',

  JUPYTER_SHARE = 'JUPYTER_SHARE',
  JUPYTER_SHARE_SUCCESS = 'JUPYTER_SHARE_SUCCESS',
  JUPYTER_SHARE_FAILURE = 'JUPYTER_SHARE_FAILURE',
  JUPYTER_SHARE_SELECTION = 'JUPYTER_SHARE_SELECTION',

  JUPYTER_INSERT = 'JUPYTER_INSERT',

  JUPYTER_SEARCH = 'JUPYTER_SEARCH',
  JUPYTER_SEARCH_SUCCESS = 'JUPYTER_SEARCH_SUCCESS',
  JUPYTER_SEARCH_FAILURE = 'JUPYTER_SEARCH_FAILURE',
  JUPYTER_QUICK_SEARCH_HOTKEY = 'JUPYTER_QUICK_SEARCH_HOTKEY',

  JUPYTER_VIEW_MATERIAL_LIST = 'JUPYTER_VIEW_SNIPPET_LIST',
  JUPYTER_VIEW_CHATBOT = 'JUPYTER_VIEW_CHATBOT',
  JUPYTER_SHOW_EXPANDED_VIEW = 'JUPYTER_SHOW_EXPANDED_VIEW',
  JUPYTER_TOGGLE_VIEW_HOTKEY = 'JUPYTER_TOGGLE_VIEW_HOTKEY',

  JUPYTER_EDIT_MATERIAL = 'JUPYTER_EDIT_SNIPPET',
  JUPYTER_EDIT_MATERIAL_SUCCESS = 'JUPYTER_EDIT_SNIPPET_SUCCESS',
  JUPYTER_EDIT_MATERIAL_FAILURE = 'JUPYTER_EDIT_SNIPPET_FAILURE',

  JUPYTER_AI_ASSISTANT_QUESTION_ASKED = 'JUPYTER_AI_ASSISTANT_QUESTION_ASKED',
  JUPYTER_AI_ASSISTANT_QUESTION_SUCCESS = 'JUPYTER_AI_ASSISTANT_QUESTION_SUCCESS',
  JUPYTER_AI_ASSISTANT_QUESTION_FAILURE = 'JUPYTER_AI_ASSISTANT_QUESTION_FAILURE',

  JUPYTER_AI_ASSISTANT_RESET = 'JUPYTER_AI_ASSISTANT_RESET',
  JUPYTER_AI_ASSISTANT_REPROMPT = 'JUPYTER_AI_ASSISTANT_REPROMPT',
  JUPYTER_AI_ASSISTANT_CLICKED_SUGGESTED_QUERY = 'JUPYTER_AI_ASSISTANT_CLICKED_SUGGESTED_QUERY',
  JUPYTER_AI_ASSISTANT_OPEN_RELEVANT_FILE = 'JUPYTER_AI_ASSISTANT_OPEN_RELEVANT_FILE',

  JUPYTER_MATERIAL_DISCOVERY = 'JUPYTER_SNIPPET_DISCOVERY',
  JUPYTER_MATERIAL_DISCOVERY_SUCCESS = 'JUPYTER_SNIPPET_DISCOVERY_SUCCESS',
  JUPYTER_MATERIAL_DISCOVERY_FAILURE = 'JUPYTER_SNIPPET_DISCOVERY_FAILURE',

  JUPYTER_REFRESH_CLICKED = 'JUPYTER_REFRESH_CLICKED',
  JUPYTER_REFRESH_HOTKEY = 'JUPYTER_REFRESH_HOTKEY',
}
