# coding: utf-8

"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    The version of the OpenAPI document: 2.11.4
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://openapi-generator.tech
"""

import unittest

import galv
from galv.model.paginated_additional_s3_storage_type_list import PaginatedAdditionalS3StorageTypeList
from galv import configuration


class TestPaginatedAdditionalS3StorageTypeList(unittest.TestCase):
    """PaginatedAdditionalS3StorageTypeList unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
