from .component import uSwidComponent as uSwidComponent
from .errors import NotSupportedError as NotSupportedError
from .purl import uSwidPurl as uSwidPurl
from .vex_document import uSwidVexDocument as uSwidVexDocument
from .vex_statement import uSwidVexStatement as uSwidVexStatement
from typing import Generator

class uSwidContainer:
    vex_documents: list[uSwidVexDocument]
    def __init__(self, components: list[uSwidComponent] | None = None) -> None: ...
    def __iter__(self) -> Generator: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item): ...
    def depsolve(self) -> None: ...
    def append(self, component: uSwidComponent) -> None: ...
    def add_vex_document(self, vex_document: uSwidVexDocument) -> None: ...
    def merge(self, component: uSwidComponent) -> uSwidComponent | None: ...
    def get_default(self) -> uSwidComponent | None: ...
    def get_by_id(self, tag_id: str, fuzzy: bool = False) -> uSwidComponent | None: ...
    def get_by_link_href(self, url: str) -> uSwidComponent | None: ...
