from .enums import uSwidVersionScheme as uSwidVersionScheme

class uSwidVcs:
    filepath: str
    dirpath: str
    def __init__(self, filepath: str, dirpath: str | None = None) -> None: ...
    def get_tag(self) -> str: ...
    def get_version(self) -> str: ...
    def get_branch(self) -> str: ...
    def get_commit(self) -> str: ...
    def get_toplevel(self) -> str | None: ...
    def get_remote_url(self) -> str | None: ...
    def get_sbom_authors(self, threshold: int = 10) -> list[str]: ...
    def get_authors(self, threshold: int = 5, relpath: str | None = None) -> list[str]: ...
