"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asninfo import AsnInfo, AsnInfoTypedDict
from .countryinfo import CountryInfo, CountryInfoTypedDict
from .locationinfo import LocationInfo, LocationInfoTypedDict
from geoipapi.types import BaseModel
from typing_extensions import TypedDict


class GeoIPResponseTypedDict(TypedDict):
    ip: str
    type: str
    country: CountryInfoTypedDict
    location: LocationInfoTypedDict
    asn: AsnInfoTypedDict


class GeoIPResponse(BaseModel):
    ip: str

    type: str

    country: CountryInfo

    location: LocationInfo

    asn: AsnInfo
