from typing import List

from numpy import ndarray

def read_layers(folder: str) -> ndarray: ...
def read_selected_layers(file_list: List[str]) -> ndarray: ...
def read_layer(file: str) -> ndarray: ...
