# Generated by Django 4.2.19 on 2025-03-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('hr_access', 'Can access HR Centre'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CorporationSetup',
            fields=[
                ('corporation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='hrcentre_setup', serialize=False, to='eveonline.evecorporationinfo')),
                ('access_list', models.ManyToManyField(blank=True, related_name='+', to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AllianceSetup',
            fields=[
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='hrcentre_setup', serialize=False, to='eveonline.eveallianceinfo')),
                ('access_list', models.ManyToManyField(blank=True, related_name='+', to='auth.group')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
