from .component import uSwidComponent as uSwidComponent
from .container import uSwidContainer as uSwidContainer

class uSwidFormatBase:
    name: str
    verbose: bool
    def __init__(self, name: str, verbose: bool = False) -> None: ...
    def load(self, blob: bytes, path: str | None = None) -> uSwidContainer: ...
    def save(self, container: uSwidContainer) -> bytes: ...
    def incorporate(self, container: uSwidContainer, component: uSwidComponent) -> None: ...
