
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-16T09:56:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b1c38f5e61b64ff2da35360d6e2f40d56a9bde8",
 "version": "1.33.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
