# generated by datamodel-codegen:
#   filename:  materials_category/defects/enums/point_defect_type.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum


class PointDefectTypeEnum(Enum):
    vacancy = "vacancy"
    substitution = "substitution"
    interstitial = "interstitial"
