author_list = [
    "William Shakespeare",
    "Jane Austen",
    "Charles Dickens",
    "Leo Tolstoy",
    "Fyodor Dostoevsky",
    "Mark Twain",
    "Ernest Hemingway",
    "Virginia Woolf",
    "James Joyce",
    "George Orwell",
    "Franz Kafka",
    "Gabriel García Márquez",
    "Marcel Proust",
    "Toni Morrison",
    "Harper Lee",
    "J.R.R. Tolkien",
    "C.S. Lewis",
    "Aldous Huxley",
    "Kurt Vonnegut",
    "John Steinbeck",
    "J.D. Salinger",
    "George Eliot",
    "Emily Brontë",
    "Charlotte Brontë",
    "Louisa May Alcott",
    "Herman Melville",
    "Nathaniel Hawthorne",
    "Edgar Allan Poe",
    "Walt Whitman",
    "Emily Dickinson",
    "Sylvia Plath",
    "Robert Frost",
    "W.B. Yeats",
    "T.S. Eliot",
    "Langston Hughes",
    "Maya Angelou",
    "Jack Kerouac",
    "Hunter S. Thompson",
    "Stephen King",
    "Agatha Christie",
    "Arthur Conan Doyle",
    "Edith Wharton",
    "Henry James",
    "Joseph Conrad",
    "D.H. Lawrence",
    "Ralph Ellison",
    "F. Scott Fitzgerald",
    "William Faulkner",
    "E.L. Doctorow",
    "Ian McEwan",
    "Salman Rushdie",
    "Orhan Pamuk",
    "Kazuo Ishiguro",
    "Margaret Atwood",
    "Philip Roth",
    "John Updike",
    "Don DeLillo",
    "Cormac McCarthy",
    "Thomas Pynchon",
    "Michael Chabon",
    "Neil Gaiman",
    "George R.R. Martin",
    "Ursula K. Le Guin",
    "Ray Bradbury",
    "Isaac Asimov",
    "Arthur C. Clarke",
    "Frank Herbert",
    "William Gibson",
    "Robert A. Heinlein",
    "Octavia E. Butler",
    "H.G. Wells",
    "Mary Shelley",
    "Jules Verne",
    "Anne Rice",
    "Clive Barker",
    "John Grisham",
    "Tom Clancy",
    "Dan Brown",
    "Paulo Coelho",
    "Eckhart Tolle",
    "Jane Eyre Brontë (Charlotte)",
    "Louisa May Alcott",
    "J.K. Rowling",
    "Suzanne Collins",
    "Stephenie Meyer",
    "Rick Riordan",
    "Veronica Roth",
    "John Green",
    "Rainbow Rowell",
    "John le Carré",
    "Val McDermid",
    "Patricia Cornwell",
    "Stieg Larsson",
    "Gillian Flynn",
    "Donna Tartt",
    "Jhumpa Lahiri",
    "Zadie Smith",
    "Chimamanda Ngozi Adichie",
    "Arundhati Roy",
    "Khaled Hosseini",
    "Elena Ferrante",
    "Jhumpa Lahiri",
    "Isabel Allende",
    "Laura Esquivel",
    "Carlos Ruiz Zafón",
    "Roberto Bolaño",
    "Jorge Luis Borges",
    "Pablo Neruda",
    "Octavio Paz",
    "Mario Vargas Llosa",
    "Alejo Carpentier",
    "José Saramago",
    "Eça de Queirós",
    "Fernández",
    "J.M. Coetzee",
    "Chinua Achebe",
    "Ngũgĩ wa Thiong'o",
    "Naguib Mahfouz",
    "Tayeb Salih",
    "Assia Djebar",
    "Dodie Smith",
    "Pat Barker",
    "Iain Banks",
    "Margaret Wise Brown",
    "Roald Dahl",
    "Beatrix Potter",
    "Dr. Seuss",
    "Maurice Sendak",
    "Shel Silverstein",
    "E.B. White",
    "C.S. Lewis",
    "A.A. Milne",
    "Enid Blyton",
    "Louis Sachar",
    "Beverly Cleary",
    "Judy Blume",
    "Eric Carle",
    "Chris Van Allsburg",
    "Eoin Colfer",
    "Cornelia Funke",
    "Geronimo Stilton",
    "Kate DiCamillo",
    "Jacqueline Wilson",
    "Andrew Clements",
    "Lemony Snicket",
    "Daniel Handler",
    "Mo Willems",
    "David Walliams",
    "Jeff Kinney",
    "Rick Riordan",
    "Diana Wynne Jones",
    "Tove Jansson",
    "Astrid Lindgren",
    "Maurice Pate",
    "Daniel Defoe",
    "Jonathan Swift",
    "Voltaire",
    "Jean-Jacques Rousseau",
    "Denis Diderot",
    "Homer",
    "Virgil",
    "Dante Alighieri",
    "John Milton",
    "Geoffrey Chaucer",
    "Miguel de Cervantes",
    "Murasaki Shikibu",
    "Laozi",
    "Sun Tzu",
    "Confucius",
    "Rumi",
    "Khalil Gibran",
    "Rabindranath Tagore",
    "Alexander Pushkin",
    "Leo Tolstoy",
    "Fyodor Dostoevsky",
    "Anton Chekhov",
    "Nikolai Gogol",
    "Ivan Turgenev",
    "Boris Pasternak",
    "Vladimir Nabokov",
    "Mikhail Bulgakov",
    "Orhan Pamuk",
    "Yevgeny Zamyatin",
    "Aleksandr Solzhenitsyn",
    "Margaret Mead",
    "Claude Lévi-Strauss",
    "Noam Chomsky",
    "Michel Foucault",
    "Pierre Bourdieu",
    "Jean-Paul Sartre",
    "Albert Camus",
    "Simone de Beauvoir",
    "Frantz Fanon",
    "bell hooks",
    "Judith Butler",
    "Gayatri Spivak",
    "Edward Said",
    "Paulo Freire",
    "Cornel West",
    "Howard Zinn",
    "E.P. Thompson",
    "Herodotus",
    "Thucydides",
    "Edward Gibbon",
    "Graham Greene",
    "John Steinbeck",
    "Vladimir Nabokov",
    "Arthur Miller",
    "Tennessee Williams",
    "Samuel Beckett",
    "Antonin Artaud",
    "Bertolt Brecht",
    "August Strindberg",
    "Henrik Ibsen",
    "Aristophanes",
    "Sophocles",
    "Euripides",
    "William Butler Yeats",
    "Seamus Heaney",
    "Federico García Lorca",
    "Pablo Neruda",
    "Allen Ginsberg",
    "Jack Kerouac",
    "Lawrence Ferlinghetti",
    "Ted Hughes",
    "Dylan Thomas",
    "Maya Angelou",
    "Robert Hayden",
    "Allen Tate",
    "Rita Dove",
    "Billy Collins",
    "Joy Harjo",
    "Louise Glück",
    "Terrance Hayes",
    "Ocean Vuong",
    "Amanda Gorman",
    "Elizabeth Bishop",
    "Anne Sexton",
    "Adrienne Rich",
    "Sylvia Plath",
    "Sharon Olds",
    "Carol Ann Duffy",
    "Margaret Atwood",
    "Alice Walker",
    "Zadie Smith",
    "Nicholson Baker",
    "Richard Powers",
    "Jonathan Franzen",
    "Ann Patchett",
    "Jhumpa Lahiri",
    "Elena Ferrante",
    "Colm Tóibín",
    "Sally Rooney",
    "Patrick Modiano",
    "Michel Houellebecq",
    "David Mitchell",
    "Kazuo Ishiguro",
    "Ian McEwan",
    "Sebastian Faulks",
    "Emma Donoghue",
    "Kate Atkinson",
    "Hilary Mantel",
    "Philippa Gregory",
    "Bernard Cornwell",
    "Ken Follett",
    "Robert Harris",
    "John le Carré",
    "Len Deighton",
    "John Grisham",
    "Scott Turow",
    "Michael Connelly",
    "James Patterson",
    "Lee Child",
    "Stieg Larsson",
    "Henning Mankell",
    "Keigo Higashino",
    "Harlan Coben",
    "Tana French",
    "Barbara Kingsolver",
    "Anita Brookner",
    "Muriel Spark",
    "Pat Barker",
    "Iain Banks",
    "Ian Rankin",
    "Val McDermid",
    "Sara Paretsky",
    "Sue Grafton",
    "Elizabeth George",
    "Sue Monk Kidd",
    "Taylor Jenkins Reid",
    "Celeste Ng",
    "Ann Leckie",
    "Becky Chambers",
    "Seanan McGuire",
    "N.K. Jemisin",
    "Brandon Sanderson",
    "Patrick Rothfuss",
    "George R.R. Martin",
    "Terry Pratchett",
    "Neil Gaiman",
    "J.R.R. Tolkien",
    "J.K. Rowling",
    "C.S. Lewis",
    "Philip Pullman",
    "Madeleine L'Engle",
    "Ursula K. Le Guin",
    "Octavia E. Butler",
    "Lois McMaster Bujold",
    "David Weber",
    "Anne McCaffrey",
    "Stephen R. Donaldson",
    "Robin Hobb",
    "Robert Jordan",
    "Janny Wurts",
    "N.K. Jemisin",
    "Peter S. Beagle",
    "Guy Gavriel Kay",
    "Octavio Paz",
    "Mario Vargas Llosa",
    "Jorge Luis Borges",
    "Pablo Neruda",
    "Isabel Allende",
    "Carlos Fuentes",
    "Roberto Bolaño",
    "Alejo Carpentier",
    "José Saramago",
    "Eça de Queirós",
    "Clarice Lispector",
    "Paulo Coelho",
    "Chinua Achebe",
    "Ngũgĩ wa Thiong'o",
    "J.M. Coetzee",
    "Naguib Mahfouz",
    "Assia Djebar",
    "Orhan Pamuk",
    "Elif Shafak",
    "Teolinda Gersão",
    "Kiran Desai",
    "Aravind Adiga",
    "Jhumpa Lahiri",
    "Salman Rushdie",
    "Khaled Hosseini",
    "Elena Ferrante",
    "Almudena Grandes",
    "Laura Restrepo",
    "Herta Müller",
    "Imre Kertész",
    "Milan Kundera",
    "Jaroslav Hašek",
    "Ivan Klíma",
    "Christos Tsiolkas",
    "Peter Carey",
    "Tim Winton",
    "David Malouf",
    "Banana Yoshimoto",
    "Haruki Murakami",
    "Yasunari Kawabata",
    "Kenzaburō Ōe",
    "Natsuo Kirino",
    "Keigo Higashino",
    "Shūsaku Endō",
    "Murasaki Shikibu",
    "Yoko Tawada",
    "Han Kang",
    "Kim Young-ha",
    "Pachinko (Min Jin Lee?)",
    "Andrea Levy",
    "Zadie Smith",
    "Salley Vickers",
    "Ali Smith",
    "Jeanette Winterson",
    "Rose Tremain",
    "Colm Tóibín",
    "Anne Enright",
    "Sally Rooney",
    "Emily St. John Mandel",
    "Jean Rhys",
    "Jean-Paul Sartre",
    "Albert Camus",
    "Simone de Beauvoir",
    "Maurice Blanchot",
    "Marguerite Duras",
    "Colette",
    "Marcel Proust",
    "Gustave Flaubert",
    "Émile Zola",
    "Victor Hugo",
    "Albertine Sarrazin",
    "Julien Green",
    "Jean Giono",
    "Annie Ernaux",
    "Édouard Louis",
    "Patrick Modiano",
    "Leïla Slimani",
    "Assia Djebar",
    "Tahmima Anam",
    "Amitav Ghosh",
    "Salman Rushdie",
    "V.S. Naipaul",
    "Arundhati Roy",
    "Kamila Shamsie",
    "Doris Lessing",
    "Nawal El Saadawi",
    "Tayeb Salih",
    "Ahdaf Soueif",
    "Ali Bader",
    "Mohsin Hamid",
    "Sabahattin Ali",
    "Orhan Pamuk",
    "Elena Ferrante",
    "Jessica Anthony",
    "Jhumpa Lahiri",
    "Gao Xingjian",
    "Mo Yan",
    "Lao She",
    "Yiyun Li",
    "Ha Jin",
    "Eileen Chang",
    "Amy Tan",
    "Maxine Hong Kingston",
    "Cathy Park Hong",
    "Ralph Ellison",
    "James Baldwin",
    "Richard Wright",
    "Toni Morrison",
    "Maya Angelou",
    "Alice Walker",
    "Zora Neale Hurston",
    "Octavia E. Butler",
    "Tananarive Due",
    "N.K. Jemisin",
    "Octavia E. Butler",
    "Nnedi Okorafor",
    "Chimamanda Ngozi Adichie",
    "Ngũgĩ wa Thiong'o",
    "Ben Okri",
    "Teju Cole",
    "Yaa Gyasi",
    "Nathacha Appanah",
    "Isabel Allende",
    "Julia de Burgos",
    "May Ziadeh",
    "Ghassan Kanafani",
    "Mahmoud Darwish",
    "Edward Said",
    "Elias Khoury",
    "Eleanor Catton",
    "Alan Duff",
    "Keri Hulme",
    "Witi Ihimaera",
    "Pat Barker",
    "Iain Banks",
    "Ian Rankin",
    "Val McDermid",
    "Robert Harris",
    "Ken Follett",
    "Wilbur Smith",
    "Paulo Coelho",
    "Michael Ondaatje",
    "Margaret Atwood",
    "Alice Munro",
    "Mavis Gallant",
    "Margaret Laurence",
    "Carol Shields",
    "Lucy Maud Montgomery",
    "Ethel Wilson",
    "Richmal Crompton",
    "PG Wodehouse",
    "H.E. Bates",
    "Nevil Shute",
    "Stieg Larsson",
    "Liza Marklund",
    "Camilla Läckberg",
    "Jo Nesbø",
    "Henning Mankell",
    "Karin Fossum",
    "Maj Sjöwall",
    "Anders Roslund",
    "Jussi Adler-Olsen",
    "George R.R. Martin",
    "J.R.R. Tolkien",
    "C.S. Lewis",
    "Philip Pullman",
    "Ursula K. Le Guin",
    "Terry Pratchett",
    "Neil Gaiman",
    "Robert Jordan",
    "Brandon Sanderson",
    "Patrick Rothfuss",
    "David Eddings",
    "Anne McCaffrey",
    "Juliet Marillier",
    "Sharon Shinn",
    "Nancy Kress",
    "Elizabeth Moon",
    "Lois McMaster Bujold",
    "Catherine Asaro",
    "Mercedes Lackey",
    "Robin Hobb",
    "Glen Cook",
    "Steven Erikson",
    "George R.R. Martin",
    "Brent Weeks",
    "Jim Butcher",
    "Jim C. Hines",
    "Seanan McGuire",
    "Robin Hobb",
    "Naomi Novik",
    "Nnedi Okorafor",
    "Sarah J. Maas",
    "Trudi Canavan",
    "Liu Cixin",
    "Lian Hearn",
    "Guy Gavriel Kay",
    "Ken Liu",
    "Andrea Camilleri",
    "Elena Ferrante",
    "Roberto Saviano",
    "Joanna Trollope",
    "Russell Hoban",
    "Iain M. Banks",
    "Alain de Botton",
    "AJ Jacobs",
    "Malcolm Gladwell",
    "Oliver Sacks",
    "Steven Johnson",
    "Eric Schlosser",
    "Rebecca Skloot",
    "Tracy Kidder",
    "Andrew Roberts",
    "Simon Sebag Montefiore",
    "Walter Isaacson",
    "Doris Kearns Goodwin",
    "Robert Caro",
    "Taylor Branch",
    "David McCullough",
    "Ken Burns (author)",
    "Michael Lewis",
    "Niall Ferguson",
    "Yuval Noah Harari",
    "Erik Larson",
    "Jared Diamond",
    "Jillian Tamaki",
    "Marjane Satrapi",
    "Alison Bechdel",
]
