genre_list = [
    # Broad Fiction
    "Literary Fiction",
    "Commercial Fiction",
    "Popular Fiction",
    "Genre Fiction",
    "Mainstream Fiction",
    "Contemporary Fiction",
    "Classic Fiction",
    "Experimental Fiction",
    "Speculative Fiction",
    # Adventure & Action
    "Adventure",
    "Action and Adventure",
    "Survival Fiction",
    "Quest Fiction",
    "Sea Adventure",
    "Jungle Adventure",
    "Spy Adventure",
    # Crime & Mystery
    "Crime Fiction",
    "Detective Fiction",
    "Cozy Mystery",
    "Hardboiled",
    "Noir",
    "Police Procedural",
    "Legal Thriller",
    "Medical Thriller",
    "Political Thriller",
    "Psychological Thriller",
    "Techno-thriller",
    "Spy Thriller",
    "Conspiracy Thriller",
    "Espionage Fiction",
    # Suspense & Thriller (non-violent)
    "Domestic Thriller",
    "Psychological Suspense",
    "Mystery Thriller",
    "Intellectual Thriller",
    # Horror & Dark Fiction
    "Horror",
    "Gothic Horror",
    "Supernatural Horror",
    "Lovecraftian Horror",
    "Weird Horror",
    "Psychological Horror",
    "Splatterpunk",
    "Eco-Horror",
    "Body Horror",
    "Southern Gothic",
    "Occult Horror",
    # Science Fiction
    "Science Fiction",
    "Hard Science Fiction",
    "Soft Science Fiction",
    "Space Opera",
    "Military Science Fiction",
    "Cyberpunk",
    "Steampunk",
    "Dieselpunk",
    "Clockpunk",
    "Biopunk",
    "Solarpunk",
    "Nanopunk",
    "Post-Apocalyptic",
    "Dystopian",
    "Utopian",
    "Time Travel",
    "Alternate History",
    "First Contact",
    "Alien Invasion",
    "Space Colony Fiction",
    # Fantasy
    "Fantasy",
    "High Fantasy",
    "Epic Fantasy",
    "Sword and Sorcery",
    "Dark Fantasy",
    "Urban Fantasy",
    "Historical Fantasy",
    "Mythic Fantasy",
    "Fairy Tale Fantasy",
    "Gaslamp Fantasy",
    "Grimdark Fantasy",
    "Portal Fantasy",
    "Magical Realism",
    "Heroic Fantasy",
    "Light Fantasy",
    "Arthurian Fantasy",
    "Wuxia",
    "Xianxia",
    "LitRPG",
    "Progression Fantasy",
    "Flintlock Fantasy",
    "Feudal Fantasy",
    "Cozy Fantasy",
    "Science Fantasy",
    # Romantic Fiction
    "Romance",
    "Contemporary Romance",
    "Historical Romance",
    "Paranormal Romance",
    "Inspirational Romance",
    "Romantic Suspense",
    "Chick Lit",
    "Erotic Romance",
    "LGBTQ+ Romance",
    # Young Readers
    "Young Adult Fiction",
    "New Adult Fiction",
    "Middle Grade Fiction",
    "Children’s Fiction",
    "Picture Book",
    "Chapter Book",
    "Early Reader",
    "Juvenile Fiction",
    # Literary Classics
    "Classic Literature",
    "Victorian Literature",
    "Modernist Fiction",
    "Postmodern Fiction",
    "Renaissance Literature",
    # Humorous & Satire
    "Satire",
    "Parody",
    "Comedy",
    "Romantic Comedy",
    "Screwball Comedy",
    "Farce",
    "Black Comedy",
    "Humor Fiction",
    "Comic Fiction",
    # Historical
    "Historical Fiction",
    "Biographical Novel",
    "Family Saga",
    "War Novel",
    "Courtroom Drama",
    "Epic Historical Fiction",
    "Picaresque Fiction",
    "Placeholder Historical Fiction",
    # Nonfiction
    "Nonfiction",
    "Creative Nonfiction",
    "Literary Nonfiction",
    "Narrative Nonfiction",
    "Memoir",
    "Biography",
    "Autobiography",
    "Travel Writing",
    "Essay",
    "Personal Essay",
    "Lyric Essay",
    "Investigative Journalism",
    "True Crime",
    "Science Writing",
    "Science Journalism",
    "Popular Science",
    "Self-Help",
    "Inspirational Nonfiction",
    "Motivational",
    "History",
    "Military History",
    "Political History",
    "Philosophy",
    "Psychology",
    "Health & Wellness",
    "Cooking & Food Writing",
    "Nature Writing",
    "Environmental Writing",
    "Spirituality",
    "Religion",
    "Business & Economics",
    "Technology & DIY",
    "Art & Photography",
    "Music Writing",
    # Poetry & Poetic Forms
    "Poetry",
    "Lyric Poetry",
    "Narrative Poetry",
    "Epic Poetry",
    "Free Verse",
    "Prose Poetry",
    "Concrete Poetry",
    "Spoken Word",
    "Instapoetry",
    "Haiku",
    "Tanka",
    "Sonnets",
    "Ode",
    "Ballad",
    "Elegy",
    "Limerick",
    "Villanelle",
    "Pantoum",
    "Ghazal",
    "Sestina",
    # Drama & Performance
    "Drama",
    "Stage Play",
    "Tragedy",
    "Comedy (Stage)",
    "Tragicomedy",
    "Melodrama",
    "Farce (Drama)",
    "Radio Drama",
    "One-Act Play",
    "Full-Length Play",
    "Experimental Drama",
    # Oral & Folk
    "Oral Literature",
    "Epic",
    "Legend",
    "Mythology",
    "Folktale",
    "Fable",
    "Urban Legend",
    "Saga",
    "Ballad (Folk)",
    "Family Legend",
    "Tall Tale",
    # Graphic & Visual
    "Graphic Novel",
    "Comics",
    "Manga",
    "Webtoon",
    "Comic Strip",
    "Illustrated Fiction",
    "Graphic Memoir",
    "Visual Nonfiction",
    # Interactive & Digital
    "Interactive Fiction",
    "Hypertext Fiction",
    "Choice-based Fiction",
    "Gamebook",
    "Generative Literature",
    "Electronic Literature",
    "Chat Narrative",
    "AR Fiction",
    "VR Fiction",
    # Experimentation & Form
    "Flash Fiction",
    "Micro Fiction",
    "Short Story",
    "Novella",
    "Chapbook",
    "Epistolary Fiction",
    "Verse Novel",
    "Fragment Fiction",
    "Frame Story",
    "Constrained Writing",
    "Metafiction",
    "Stream-of-Consciousness",
    "Minimalist Fiction",
    "Absurdist Fiction",
    "Magical Think-Piece",
    # Niche & Thematic
    "Cli-Fi (Climate Fiction)",
    "Eco-Fiction",
    "Afrofuturism",
    "Bizarro Fiction",
    "Slipstream",
    "Weird West",
    "Southern Gothic",
    "Campus Fiction",
    "Campus Comedy",
    "Campus Drama",
    "Campus Mystery",
    "Campus Romance",
    "Campus Sci-Fi",
    "Campus Fantasy",
    "Campus Horror",
    "Campus Poetry",
    "Campus Memoir",
    "War Poetry",
    "Sales Psychology",
    "Prison Literature",
    "Slave Narrative",
    "Road Fiction",
    "Rural Fiction",
    "Suburban Fiction",
    "Urban Fiction",
    "Coastal Fiction",
    "Frontier Fiction",
    "Migrant Fiction",
    "Diaspora Fiction",
    # Genre Blends & Hybrids
    "Romantic Mystery",
    "Mystery Thriller",
    "Historical Mystery",
    "Fantasy Romance",
    "Paranormal Mystery",
    "Sci-Fi Comedy",
    "Horror Comedy",
    "Romantic Comedy Mystery",
    "Supernatural Thriller",
    "Political Satire Fiction",
    "Techno-Satire",
    # Cultural / Regional
    "Latin American Literature",
    "Magical Realism (Latin)",
    "African Literature",
    "Afro-Caribbean Fiction",
    "Asian American Fiction",
    "Postcolonial Literature",
    "Indigenous Fiction",
    "LGBTQ+ Literature",
    "Jewish Literature",
    "Muslim Fiction",
    "Christian Fiction",
    "Islamic Fiction",
    "Buddhist Fiction",
    "Celtic Fiction",
    "Nordic Noir",
    # Global Subgenres
    "Shonen Manga",
    "Shojo Manga",
    "Seinen Manga",
    "Josei Manga",
    "Manhwa",
    "Manhua",
    "Light Novel",
    "Cell-Phone Novel",
    "Fan Fiction",
    "Slash Fiction",
    "Crossover Fanfic",
    # Further micro-genres
    "Kitchen Sink Drama",
    "Post-Modern Drama",
    "Kino Drama",
    "Opera Fiction",
    "Medical Memoir",
    "Surreal Fiction",
    "Psychedelic Fiction",
    "Transgressive Fiction",
    "Cyber-noir",
    "Retro-Futurism",
    "Weird Science",
    # More niche nonfiction:
    "Food Memoir",
    "Adventure Memoir",
    "Climbing Memoir",
    "Sports Memoir",
    "Science Memoir",
    "Tech Memoir",
    "Music Memoir",
    "Political Memoir",
    "Economic Memoir",
    "Travel Memoir",
    "Humor Memoir",
    "Photography Memoir",
    "Art Memoir",
    # Very niche microgenres
    "Taxonomy Fiction",
    "Bibliomystery",
    "Epistolary Nonfiction",
    "Hybrid Memoir",
    "Flash Memoir",
    "Place Essay",
    "Nature Essay",
    "Science Poetry",
    "Nature Poetry",
    "Political Poetry",
    "War Poetry",
    "Experimental Memoir",
    "Visual Poetry",
    # ! Approaching 500
    "Railway Fiction",
    "Maritime Fiction",
    "Aviation Fiction",
    "Automotive Fiction",
    "Disaster Fiction",
    "Pandemic Fiction",
    "Cyber Romance",
    "Nano Romance",
    "Genetic Romance",
    "Bio Romance",
    "Folk Horror",
    "Cannibal Horror",
    "Quantitative Fiction",
    "Data Journalism",
    "Quantified Self Memoir",
    "Self-Publishing Memoir",
    "Startup Memoir",
    "Digital Nomad Memoir",
    "Van Life Memoir",
    "Tiny House Memoir",
    "Heritage Travel Writing",
    "Architectural Travel Writing",
    "Dark Tourism Writing",
    "Microhistory",
    "Macrohistory",
    "Conspiratorial Nonfiction",
    "Alternative History Nonfiction",
    "Metaphysical Nonfiction",
    "Polemical Nonfiction",
    "Academic Poetry",
    "Political Essay",
    "Cultural Criticism",
    "Media Criticism",
    "Digital Culture Essay",
    "UX Writing Fiction",
    "Speculative Biography",
]
