MESSAGES_COLUMN_NAME = "messages"
UNLABELED_DATA_SPLIT_DEFAULT_NAME = "train"
TEST_DATA_SPLIT_DEFAULT_NAME = "test"

DEFAULT_GPU_MEMORY_UTILIZATION = 0.5
DEFAULT_TEMPERATURE = 0.6
DEFAULT_TOP_P = 1

REASONING_END_TOKEN = "</think>"
APPROX_NUM_SYSTEM_TOKENS_PER_MESSAGE = 10

DEFAULT_CONFIG_NAME = "base"

OUTPUT_FIELD_PURPOSE_TRAIN = "train"
OUTPUT_FIELD_PURPOSE_TEST = "test"
