# generated by datamodel-codegen:
#   filename:  material/reusable/coordinate_conditions/cylinder.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class CoordinateShapeEnum(Enum):
    cylinder = "cylinder"
    sphere = "sphere"
    box = "box"
    triangular_prism = "triangular_prism"
    plane = "plane"


class CylinderCoordinateConditionSchema(BaseModel):
    shape: Literal["cylinder"] = Field(..., title="Coordinate Shape Enum")
    center_position: Optional[List[float]] = Field([0.5, 0.5], max_length=2, min_length=2)
    radius: Optional[float] = 0.25
    min_z: Optional[float] = 0
    max_z: Optional[float] = 1
