TRANSACTION_MIN_GAS_PRICE = 1000000000
TRANSACTION_VERSION_DEFAULT = 2
TRANSACTION_OPTIONS_DEFAULT = 0
ARGS_SEPARATOR = "@"
METACHAIN_ID = 4294967295
VM_TYPE_WASM_VM = bytes([0x05, 0x00])

# 64 bytes = 512 bits
INTEGER_MAX_NUM_BYTES = 64

REWA_TOKEN_IDENTIFIER = "REWA"
REWA_NUM_DECIMALS = 18

DELEGATION_MANAGER_SC_ADDRESS = "drt1yvesqqqqqqqqqqqqqqqqqqqqqqqqyvesqqqqqqqqqqqqqqqyllls4jxmwv"
DEFAULT_HRP = "drt"
CONTRACT_DEPLOY_ADDRESS = "drt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq85hk5z"
TRANSACTION_OPTIONS_TX_GUARDED = 0b0010
TRANSACTION_OPTIONS_TX_HASH_SIGN = 0b0001

DIGEST_SIZE = 32

TOKEN_RANDOM_SEQUENCE_LENGTH = 6

DEFAULT_MESSAGE_VERSION = 1
BECH32_ADDRESS_LENGTH = 62

MIN_TRANSACTION_VERSION_THAT_SUPPORTS_OPTIONS = 2
SDK_PY_SIGNER = "sdk-py"
UNKNOWN_SIGNER = "unknown"

REWA_IDENTIFIER_FOR_MULTI_DCDTNFT_TRANSFER = "REWA-000000"
