# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.discovery.v0 import monitors_pb2 as ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2


class MonitorsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMonitor = channel.unary_unary(
                '/ansys.api.discovery.v0.monitors.Monitors/CreateMonitor',
                request_serializer=ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.CreateMonitorRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.MonitorCreationResponse.FromString,
                )


class MonitorsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMonitor(self, request, context):
        """Creates a new monitor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMonitor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMonitor,
                    request_deserializer=ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.CreateMonitorRequest.FromString,
                    response_serializer=ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.MonitorCreationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.discovery.v0.monitors.Monitors', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitors(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.discovery.v0.monitors.Monitors/CreateMonitor',
            ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.CreateMonitorRequest.SerializeToString,
            ansys_dot_api_dot_discovery_dot_v0_dot_monitors__pb2.MonitorCreationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
