# Form implementation generated from reading ui file '/tmp/tmpzwjielv_/jddesktopentryedit-1.7/jdDesktopEntryEdit/ui/PreviewDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PreviewDialog(object):
    def setupUi(self, PreviewDialog):
        PreviewDialog.setObjectName("PreviewDialog")
        PreviewDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreviewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=PreviewDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.preview_edit = QtWidgets.QPlainTextEdit(parent=PreviewDialog)
        self.preview_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.preview_edit.setReadOnly(True)
        self.preview_edit.setPlainText("")
        self.preview_edit.setObjectName("preview_edit")
        self.verticalLayout.addWidget(self.preview_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copy_button = QtWidgets.QPushButton(parent=PreviewDialog)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.copy_button.setIcon(icon)
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout.addWidget(self.copy_button)
        self.close_button = QtWidgets.QPushButton(parent=PreviewDialog)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PreviewDialog)
        QtCore.QMetaObject.connectSlotsByName(PreviewDialog)

    def retranslateUi(self, PreviewDialog):
        _translate = QtCore.QCoreApplication.translate
        PreviewDialog.setWindowTitle(_translate("PreviewDialog", "Preview"))
        self.label.setText(_translate("PreviewDialog", "Preview of your desktop entry"))
        self.copy_button.setText(_translate("PreviewDialog", "Copy"))
        self.close_button.setText(_translate("PreviewDialog", "Close"))
