# Form implementation generated from reading ui file '/tmp/tmpzwjielv_/jddesktopentryedit-1.7/jdDesktopEntryEdit/ui/WelcomeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeDialog(object):
    def setupUi(self, WelcomeDialog):
        WelcomeDialog.setObjectName("WelcomeDialog")
        WelcomeDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=WelcomeDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.show_startup_check_box = QtWidgets.QCheckBox(parent=WelcomeDialog)
        self.show_startup_check_box.setObjectName("show_startup_check_box")
        self.verticalLayout.addWidget(self.show_startup_check_box)
        self.button_box = QtWidgets.QDialogButtonBox(parent=WelcomeDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(WelcomeDialog)
        self.button_box.accepted.connect(WelcomeDialog.accept) # type: ignore
        self.button_box.rejected.connect(WelcomeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WelcomeDialog)

    def retranslateUi(self, WelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        WelcomeDialog.setWindowTitle(_translate("WelcomeDialog", "Welcome"))
        self.label.setText(_translate("WelcomeDialog", "Welcome to jdDesktopEntryEdit!"))
        self.label_2.setText(_translate("WelcomeDialog", "This Program allows you to create and edit Desktop Entries according to the Freedesktop Specification."))
        self.label_3.setText(_translate("WelcomeDialog", "Unlike other Programs, which try to make things easy by implementing only the main parts, the Goal of jdDesktopEntryEdit is to support the full specification. Thefore, it is expected to read the Specification before using this Program."))
        self.label_4.setText(_translate("WelcomeDialog", "You can view the Specification at ?>Destop Entry Specification."))
        self.label_5.setText(_translate("WelcomeDialog", "You can validate your Desktop Entry at Tools>Validate."))
        self.show_startup_check_box.setText(_translate("WelcomeDialog", "Show this Dialog on Startup"))
