# coding: utf-8

"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    The version of the OpenAPI document: 2.11.4
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://openapi-generator.tech
"""

from galv.paths.cell_families_.post import CellFamiliesCreate
from galv.paths.cell_families_describe_.get import CellFamiliesDescribeRetrieve
from galv.paths.cell_families_id_.delete import CellFamiliesDestroy
from galv.paths.cell_families_.get import CellFamiliesList
from galv.paths.cell_families_id_.patch import CellFamiliesPartialUpdate
from galv.paths.cell_families_id_.get import CellFamiliesRetrieve


class CellFamiliesApi(
    CellFamiliesCreate,
    CellFamiliesDescribeRetrieve,
    CellFamiliesDestroy,
    CellFamiliesList,
    CellFamiliesPartialUpdate,
    CellFamiliesRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
