# coding: utf-8

"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    The version of the OpenAPI document: 2.11.4
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://openapi-generator.tech
"""

from galv.paths.users_.post import UsersCreate
from galv.paths.users_describe_.get import UsersDescribeRetrieve
from galv.paths.users_.get import UsersList
from galv.paths.users_id_.patch import UsersPartialUpdate
from galv.paths.users_id_.get import UsersRetrieve


class UsersApi(
    UsersCreate,
    UsersDescribeRetrieve,
    UsersList,
    UsersPartialUpdate,
    UsersRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
