# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import typing
from .tls_summary import TlsSummary
from .discover_tls_config import DiscoverTlsConfig
from .....core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DiscoverTlsReport(UniversalBaseModel):
    details: typing.Optional[typing.List[TlsSummary]] = None
    errors: typing.Optional[typing.List[str]] = None
    config: DiscoverTlsConfig

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
