# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.api.version_api import VersionApi


class TestVersionApi(unittest.TestCase):
    """VersionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VersionApi()

    def tearDown(self) -> None:
        pass

    def test_get_build_information(self) -> None:
        """Test case for get_build_information

        Software build version and timestamp.
        """
        pass


if __name__ == '__main__':
    unittest.main()
