# This script was generated by combining and prefixing multiple files.

# --- Combined External Imports ---
# No external imports found.

# -------------------- Content from: add_two_nums/my_module/test.py --------------------
mod_b9def2bc_A = 2
# -------------------- Content from: add_two_nums/__init__.py --------------------
"""Put your package code!"""

def mod_f20a0c2b_add_two_numbers(a, b):
    return a + b
# -------------------- Content from: main.py --------------------
"""
Template for the main.py file.

Eventually, DishPy will add better templates to achieve feature parity with VEXcode, but for now you're stuck with this empty file!
"""
print(mod_f20a0c2b_add_two_numbers(6, 7))

# --- End of combined script ---