
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-12T13:30:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b280c58ac55cc0ba29bbaa9ab544bb3edf019397",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
