# generated by datamodel-codegen:
#   filename:  core/abstract/point.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel


class PointSchema(RootModel[List[float]]):
    root: List[float] = Field(..., max_length=3, min_length=3, title="point schema")
