# Log messages
NEW_PAGE_CREATING = "Creating a new page in the browser context..."
NEW_PAGE_CREATED = "New page created successfully."
BROWSER_CONTEXT_OPENED = "A new browser context has been opened."
START_FUNC_EXECUTING = "Executing start function: {function_name}"
START_FUNC_EXECUTED  = "Executing start function {function_name} executed successfully."
NEW_SESSION_CREATED = "New session created successfully."
INJECT_FETCH_STARTED = "Starting inject fetch request to URL: {url}"
INJECT_FETCH_REQUEST_MODIFIED = "Request modified: {url} - Method: {method}"
INJECT_FETCH_INTERCEPTOR_SETUP = "Setting up request interceptor for URL: {url}"
INJECT_FETCH_JS_LOADING = "Loading JavaScript for inject_fetch from: {path}"
INJECT_FETCH_JS_EVALUATING = "Evaluating JavaScript with URL: {url}, Method: {method}"
INJECT_FETCH_JS_COMPLETED = "JavaScript execution completed with success: {success}"
INJECT_FETCH_ERROR = "Inject fetch error: {error_name} - {error_message}"
INJECT_FETCH_HEADERS_CAPTURED = "Request headers captured: {headers_count} headers"
INJECT_FETCH_NO_HEADERS = "No request headers were captured"
INJECT_FETCH_NO_VALID_RESPONSE = "No valid response captured, returning NetworkError"
INJECT_FETCH_INTERCEPTION_FAILED = "Interception failed: {reason}"
INJECT_FETCH_COMPLETED = "Inject fetch request completed in {duration:.3f}s"
INJECT_FETCH_REQUEST_CREATED = "Created Request object from URL: {url}"
INJECT_FETCH_REQUEST_EXISTING = "Using existing Request object with URL: {url}"
INJECT_FETCH_MODIFIER_APPLYING = "Applying request modifier function"
INJECT_FETCH_MODIFIER_AWAITED = "Awaited coroutine from request modifier function"
INJECT_FETCH_ROUTE_CLEANUP = "Cleaning up route interception"
INJECT_FETCH_ROUTE_CLEANUP_SUCCESS = "Successfully unrouted interceptor"
TARGET_CLOSED_ERROR = "Target page/browser/context was closed, skipping interception for {url}"
PAGE_CLOSED = "Page closed successfully"
CLOSING_CONNECTION = "Closing {connection_name} connection..."
CONNECTION_CLOSED = "connection was closed"
CONNECTION_NOT_OPEN = "connection was not open"
PREPARING_TO_CLOSE = "Preparing to close: {connections}"
NO_CONNECTIONS = "No connections to close"
OPENING_BROWSER = "Opening new browser connection with proxy: {proxy}"
SYSTEM_PROXY = "SYSTEM_PROXY"
REQUEST_MODIFIER_FAILED_TYPE = "request_modifier_func returned non-Request object: {object_type}"
REQUEST_MODIFIER_ANY_TYPE = "Request method ANY - is not a specific type."
PAGE_NOT_AVAILABLE = "Page is not available"

# Handler log messages
HANDLER_WILL_CAPTURE = "Handler {handler_type} will capture: {url}"
HANDLER_REJECTED = "Handler {handler_type} rejected: {url} (content-type: {content_type})"
ALL_HANDLERS_REJECTED = "All handlers rejected: {url}"
HANDLER_CAPTURED_RESPONSE = "Handler {handler_type} captured response from {url} ({current_count}/{max_responses})"
ALL_HANDLERS_COMPLETED = "All handlers reached their max_responses limits, completing..."
TIMEOUT_REACHED = "Timeout reached for multi-handler request to {base_url}. Duration: {duration:.3f}s"

# Proxy log messages
PARSING_PROXY = "Parsing proxy string: {proxy_string}"
PROXY_NOT_PROVIDED = "Proxy string not provided, checking environment variables for HTTP(S)_PROXY"
NO_PROXY_FOUND = "No proxy string found, returning None"
PROXY_FOUND_IN_ENV = "Proxy string found in environment variables"
PROXY_PARSED_BASIC = "Proxy parsed as basic"
PROXY_WITH_CREDENTIALS = "Proxy WITH credentials"
PROXY_WITHOUT_CREDENTIALS = "Proxy WITHOUT credentials"
PROXY_PARSED_REGEX = "Proxy parsed as regex"

# Connection log messages
CONNECTION_CLOSED_SUCCESS = "The {connection_name} {status}"
CONNECTION_NOT_OPEN_WARNING = "The {connection_name} {status}"

# Cleanup messages
UNROUTE_CLEANUP_ERROR_DIRECT_FETCH = "Error during unroute cleanup in direct_fetch: {error}"
UNROUTE_CLEANUP_ERROR_INJECT_FETCH = "Error during unroute cleanup in inject_fetch: {error}"

# Cookie management messages
COOKIE_ADDED = "Cookie added: {name}={value} for domain {domain}"
COOKIES_ADDED = "Added {count} cookies"
COOKIE_REMOVED = "Cookie removed: {name}"
COOKIES_REMOVED = "Removed {count} cookies"
COOKIE_NOT_FOUND = "Cookie '{name}' not found for removal"

CAMOUFOX_NOT_INSTALLED = "Camoufox is not installed. Install with 'pip install standard_open_inflation_package[camoufox]'"

# Text constants
UNLIMITED_SIZE = "unlimited"
UNKNOWN_HEADER_TYPE = "unknown"
NOTHING = "nothing"
