# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.concrete_value import ConcreteValue

class TestConcreteValue(unittest.TestCase):
    """ConcreteValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConcreteValue:
        """Test ConcreteValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConcreteValue`
        """
        model = ConcreteValue()
        if include_optional:
            return ConcreteValue(
                data_type = 'DECIMAL',
                value = '',
                value_with_prefix = ''
            )
        else:
            return ConcreteValue(
        )
        """

    def testConcreteValue(self):
        """Test ConcreteValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
