# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.api.authoring_stats_api import AuthoringStatsApi


class TestAuthoringStatsApi(unittest.TestCase):
    """AuthoringStatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthoringStatsApi()

    def tearDown(self) -> None:
        pass

    def test_get_changed_fsns(self) -> None:
        """Test case for get_changed_fsns

        """
        pass

    def test_get_inactivated_concepts(self) -> None:
        """Test case for get_inactivated_concepts

        """
        pass

    def test_get_inactivated_synonyms(self) -> None:
        """Test case for get_inactivated_synonyms

        """
        pass

    def test_get_new_concepts(self) -> None:
        """Test case for get_new_concepts

        """
        pass

    def test_get_new_descriptions(self) -> None:
        """Test case for get_new_descriptions

        """
        pass

    def test_get_new_synonyms_on_existing_concepts(self) -> None:
        """Test case for get_new_synonyms_on_existing_concepts

        """
        pass

    def test_get_per_module_counts(self) -> None:
        """Test case for get_per_module_counts

        Get counts of various components types per module id
        """
        pass

    def test_get_reactivated_concepts(self) -> None:
        """Test case for get_reactivated_concepts

        """
        pass

    def test_get_reactivated_synonyms(self) -> None:
        """Test case for get_reactivated_synonyms

        """
        pass

    def test_get_stats(self) -> None:
        """Test case for get_stats

        Calculate statistics for unreleased/unversioned content to be used in daily build browser.
        """
        pass


if __name__ == '__main__':
    unittest.main()
