# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.api.mrcm_api import MRCMApi


class TestMRCMApi(unittest.TestCase):
    """MRCMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MRCMApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_attribute_values(self) -> None:
        """Test case for retrieve_attribute_values

        Retrieve valid values for the given attribute and term prefix.
        """
        pass

    def test_retrieve_concept_model_attribute_hierarchy(self) -> None:
        """Test case for retrieve_concept_model_attribute_hierarchy

        Retrieve all active concept model attributes in a hierarchical structure.
        """
        pass

    def test_retrieve_domain_attributes(self) -> None:
        """Test case for retrieve_domain_attributes

        Retrieve MRCM domain attributes applicable for the given stated parents.
        """
        pass


if __name__ == '__main__':
    unittest.main()
