# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.api.relationships_api import RelationshipsApi


class TestRelationshipsApi(unittest.TestCase):
    """RelationshipsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RelationshipsApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_relationship(self) -> None:
        """Test case for fetch_relationship

        """
        pass

    def test_find_relationships(self) -> None:
        """Test case for find_relationships

        """
        pass


if __name__ == '__main__':
    unittest.main()
