# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.branch_review_concept_changes import BranchReviewConceptChanges

class TestBranchReviewConceptChanges(unittest.TestCase):
    """BranchReviewConceptChanges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BranchReviewConceptChanges:
        """Test BranchReviewConceptChanges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BranchReviewConceptChanges`
        """
        model = BranchReviewConceptChanges()
        if include_optional:
            return BranchReviewConceptChanges(
                changed_concepts = [
                    56
                    ]
            )
        else:
            return BranchReviewConceptChanges(
        )
        """

    def testBranchReviewConceptChanges(self):
        """Test BranchReviewConceptChanges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
