# This file was auto-generated by Fern from our API Definition.

from .......core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .......core.pydantic_utilities import IS_PYDANTIC_V2


class DiscoverDnsSubdomainActiveConfig(UniversalBaseModel):
    domain: str
    subdomains: typing.Optional[typing.List[str]] = None
    subdomain_lists: typing.Optional[typing.List[str]] = pydantic.Field(alias="subdomainLists", default=None)
    threads: typing.Optional[int] = None
    max_depth: typing.Optional[int] = pydantic.Field(alias="maxDepth", default=None)
    timeout: typing.Optional[int] = None
    dns_resolver: typing.Optional[str] = pydantic.Field(alias="dnsResolver", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
