
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-16T15:12:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6dead8e554dd0464bdfc65de24889374508f920d",
 "version": "3.0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
