from typing import Optional

class EcdhX25519:
    public_key: Optional[bytes]

    def __init__(self) -> None: ...
    def generate_keypair(self) -> bytes: ...
    def generate_shared_secret(self, another_public_key: bytes) -> bytes: ...
