"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2

class OnshapeServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    SetAuthentication: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetAuthenticationRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetAuthenticationReply,
    ]
    """Sets Onshape authentication and ties it to Luminary authentication."""
    GetAuthenticationStatus: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationReply,
    ]
    """Checks whether Luminary user currently has valid Auth for Onshape."""
    ImportGeometry: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.ImportGeometryRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.ImportGeometryReply,
    ]
    """Imports geometry from Onshape into a Luminary Project."""
    FetchVariables: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesReply,
    ]
    """Get the current list of variables used in an Onshape project."""
    SetVariables: grpc.UnaryUnaryMultiCallable[
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetVariablesRequest,
        luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetVariablesReply,
    ]
    """Resets variables in an Onshape project."""

class OnshapeServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SetAuthentication(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetAuthenticationRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetAuthenticationReply:
        """Sets Onshape authentication and ties it to Luminary authentication."""
    @abc.abstractmethod
    def GetAuthenticationStatus(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.GetAuthenticationReply:
        """Checks whether Luminary user currently has valid Auth for Onshape."""
    @abc.abstractmethod
    def ImportGeometry(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.ImportGeometryRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.ImportGeometryReply:
        """Imports geometry from Onshape into a Luminary Project."""
    @abc.abstractmethod
    def FetchVariables(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.FetchVariablesReply:
        """Get the current list of variables used in an Onshape project."""
    @abc.abstractmethod
    def SetVariables(
        self,
        request: luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetVariablesRequest,
        context: grpc.ServicerContext,
    ) -> luminarycloud._proto.api.v0.luminarycloud.thirdpartyintegration.onshape.onshape_pb2.SetVariablesReply:
        """Resets variables in an Onshape project."""

def add_OnshapeServiceServicer_to_server(servicer: OnshapeServiceServicer, server: grpc.Server) -> None: ...
