# coding: utf-8

"""
    Battery Data API

    A standard API for accessing battery experiment datasets and metadata  # noqa: E501

    The version of the OpenAPI document: 2.11.4
    Contact: martin.robinson@cs.ox.ac.uk
    Generated by: https://openapi-generator.tech
"""

from galv.paths.units_.post import UnitsCreate
from galv.paths.units_describe_.get import UnitsDescribeRetrieve
from galv.paths.units_.get import UnitsList
from galv.paths.units_id_.patch import UnitsPartialUpdate
from galv.paths.units_id_.get import UnitsRetrieve


class UnitsApi(
    UnitsCreate,
    UnitsDescribeRetrieve,
    UnitsList,
    UnitsPartialUpdate,
    UnitsRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
