"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from zendesk import utils
from zendesk.models import (
    skillbasedroutingattributevalueserror as models_skillbasedroutingattributevalueserror,
)
from zendesk.types import BaseModel


class SkillBasedRoutingAttributeValuesErrorData(BaseModel):
    error: Optional[
        models_skillbasedroutingattributevalueserror.SkillBasedRoutingAttributeValuesErrorError
    ] = None


class SkillBasedRoutingAttributeValuesError(Exception):
    data: SkillBasedRoutingAttributeValuesErrorData

    def __init__(self, data: SkillBasedRoutingAttributeValuesErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, SkillBasedRoutingAttributeValuesErrorData)
