
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-13T19:08:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d388d1c6fec8cb3a0eebee5b5a0b9776ca59ca83",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
