# generated by datamodel-codegen:
#   filename:  core/reusable/accuracy_level.json
#   version:   0.25.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class ReusableAccuracyLevelsSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    standard: Optional[float] = None
    """
    Parameter value for standard or default accuracy calculation.
    """
    high: Optional[float] = None
    """
    Parameter value for high precision calculation.
    """
    low: Optional[float] = None
    """
    Parameter value for low precision calculation.
    """
