# Generated by Django 4.2.19 on 2025-04-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0118_alter_skill_id'),
        ('hrcentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAuditLoginData',
            fields=[
                ('characteraudit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='login_data', serialize=False, to='corptools.characteraudit')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
