"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class WebhookInvocationStatus(str, Enum):
    UNKNOWN = "unknown"
    ACCEPTED = "accepted"
    SUCCESS = "success"
    FAILED = "failed"
    TIMEOUT = "timeout"
    CIRCUIT_BROKEN = "circuit broken"
    THROTTLED = "throttled"
    CLIENT_ERROR = "client error"
    SERVER_ERROR = "server error"


class WebhookInvocationTypedDict(TypedDict):
    id: NotRequired[str]
    webhook_id: NotRequired[str]
    status: NotRequired[WebhookInvocationStatus]
    created_at: NotRequired[datetime]
    latest_completed_at: NotRequired[datetime]


class WebhookInvocation(BaseModel):
    id: Optional[str] = None

    webhook_id: Optional[str] = None

    status: Optional[WebhookInvocationStatus] = None

    created_at: Optional[datetime] = None

    latest_completed_at: Optional[datetime] = None
