"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhookauthentication import WebhookAuthentication, WebhookAuthenticationTypedDict
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict
from zendesk.types import BaseModel


class WebhookTestRequestWebhookTypedDict(TypedDict):
    r"""Webhook configuration for testing"""

    endpoint: NotRequired[str]
    http_method: NotRequired[str]
    request_format: NotRequired[str]
    authentication: NotRequired[WebhookAuthenticationTypedDict]
    r"""Adds authentication to the webhook's HTTP requests"""
    custom_headers: NotRequired[Dict[str, str]]


class WebhookTestRequestWebhook(BaseModel):
    r"""Webhook configuration for testing"""

    endpoint: Optional[str] = None

    http_method: Optional[str] = None

    request_format: Optional[str] = None

    authentication: Optional[WebhookAuthentication] = None
    r"""Adds authentication to the webhook's HTTP requests"""

    custom_headers: Optional[Dict[str, str]] = None


class WebhookTestRequestTypedDict(TypedDict):
    webhook: NotRequired[WebhookTestRequestWebhookTypedDict]
    r"""Webhook configuration for testing"""


class WebhookTestRequest(BaseModel):
    webhook: Optional[WebhookTestRequestWebhook] = None
    r"""Webhook configuration for testing"""
