# This file is automatically generated by ../package_info.py 
__version__: str = '2025.6.12.201824'
__build_time__: str = '2025-06-12T20:18:24.650337+00:00'
__commit__: str = 'f2238425d6567b266582c2cc5d73869bf0e4963a'
