
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-13T14:42:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f393f27b4e273646f4fdf425dfdba8d865099917",
 "version": "0.5.1rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
