# Generated by Django 3.2.4 on 2021-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=128, null=True)),
                ('text', models.TextField(null=True)),
                ('model', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
