# Generated by Django 3.2.4 on 2021-07-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
