from __future__ import annotations

from ..data import DNASeq

class DNARecord:
    @property
    def sequence(self) -> DNASeq: ...
    @property
    def description(self) -> str: ...
    @property
    def id(self) -> str: ...

class DNAReader:
    def __init__(self, path: str): ...
    def __iter__(self) -> DNAReader: ...
    def __next__(self) -> DNARecord: ...
