
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-12T18:57:31-0300",
 "dirty": true,
 "error": null,
 "full-revisionid": "14baaf4b4e688a68ff32098124e78e6bab89dcb5",
 "version": "2.63.3b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
