# generated by datamodel-codegen:
#   filename:  core/primitive/3d_lattice.json
#   version:   0.25.5

from __future__ import annotations

from pydantic import BaseModel


class Field3DimensionalLatticeSchema(BaseModel):
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """
