publisher_list = [
    # Big Five & major conglomerates
    "Penguin Random House",
    "HarperCollins",
    "Simon & Schuster",
    "Hachette Book Group",
    "Macmillan Publishers",
    "Scholastic Corporation",
    "Houghton Mifflin Harcourt",
    "Wiley",
    "Pearson Education",
    "Cengage Learning",
    "McGraw-Hill Education",
    "Elsevier",
    "Springer Nature",
    "Thomson Reuters",
    "Taylor & Francis",
    # University presses (larger)
    "Oxford University Press",
    "Cambridge University Press",
    "MIT Press",
    "Yale University Press",
    "Harvard University Press",
    "University of Chicago Press",
    "Princeton University Press",
    "Columbia University Press",
    "Cornell University Press",
    "Duke University Press",
    "Johns Hopkins University Press",
    "Stanford University Press",
    "California University Press",
    "University of Pennsylvania Press",
    "Northwestern University Press",
    # Academic & professional
    "Routledge",
    "SAGE Publications",
    "Elsevier Science",
    "Springer",
    "Palgrave Macmillan",
    "Wiley-Blackwell",
    "CRC Press",
    "McFarland & Company",
    "Edward Elgar Publishing",
    # Trade imprints (PRH)
    "Viking",
    "Crown",
    "Doubleday",
    "Riverhead Books",
    "Random House",
    "Ballantine Books",
    "Knopf",
    "Bantam Books",
    "Del Rey",
    "Scholastic Press",
    "Little, Brown and Company",
    "St. Martin's Press",
    "Farrar, Straus and Giroux",
    "Picador",
    "Knopf Doubleday Publishing Group",
    "Pantheon Books",
    # Trade imprints (HC)
    "William Morrow",
    "Avon Books",
    "Harper",
    "Harper Voyager",
    "Ecco Press",
    "Thomas Dunne Books",
    "ReganArts",
    # Trade imprints (HMH)
    "HMH Books",
    "Clarion Books",
    "Graphia",
    "Versify",
    # Trade imprints (Hachette)
    "Little, Brown",
    "Orbit",
    "Grand Central Publishing",
    "Little, Brown UK",
    "Abacus",
    "Constable & Robinson",
    # Trade imprints (Macmillan)
    "Tor Books",
    "Pan Macmillan",
    "Farrar Straus and Giroux",
    "Henry Holt",
    "St. Martin's Press",
    "Picador (US)",
    # Genre/Speculative Fiction
    "DAW Books",
    "Night Shade Books",
    "Subterranean Press",
    "Baen Books",
    "Pyr (Prometheus Books)",
    "Titan Books",
    "Gollancz",
    "ChiZine Publications",
    "Edge Science Fiction and Fantasy",
    # Young Adult & Children’s
    "Candlewick Press",
    "Nosy Crow",
    "Barefoot Books",
    "Capstone",
    "Lee & Low Books",
    "Chronicle Books",
    "Nosy Crow",
    "Akashic Books",
    "Sourcebooks",
    # Independent US presses
    "Grove Atlantic",
    "Graywolf Press",
    "Milkweed Editions",
    "Europa Editions",
    "Coffee House Press",
    "Melville House",
    "Seven Stories Press",
    "Soft Skull Press",
    "Akashic Books",
    "Tin House Books",
    "Catapult",
    "Red Hen Press",
    "Algonquin Books",
    "Beacon Press",
    "Workman Publishing",
    "New Directions",
    "Verso Books",
    "Haymarket Books",
    "Open Letter Books",
    "Archipelago Books",
    "City Lights Publishers",
    "Dalkey Archive Press",
    "Coffee House Press",
    "Counterpoint",
    "HarperVia",
    "Zando",
    # Poetry & small literary
    "Wave Books",
    "Alice James Books",
    "Copper Canyon Press",
    "BOA Editions",
    "Tupelo Press",
    "Persea Books",
    "Milkweed Editions",
    "Red Hen Press",
    "Copper Canyon Press",
    "Graywolf Press",
    "Fence Books",
    "UglyDuckling Presse",
    "City Lights Publishers",
    "Akashic Books",
    "Norton Poetry Series",
    "Carcanet Press",
    "Bloodaxe Books",
    "Carcanet Press",
    "Shearsman Books",
    # Regional/Non-English
    "Gallimard",
    "Fondo de Cultura Económica",
    "Grupo Planeta",
    "Anagrama",
    "Alianza Editorial",
    "Bloomsbury India",
    "Yunus Emre Enstitüsü",
    "Köln University Press",
    "Hanser Verlag",
    "Suhrkamp Verlag",
    "Random House Mondadori",
    "Editora Record",
    "Companhia das Letras",
    "Edelvives",
    "Editorial An Māland",
    # Religious & inspirational
    "Zondervan",
    "Thomas Nelson",
    "Baker Publishing Group",
    "Tyndale House",
    "NavPress",
    "Moody Publishers",
    "InterVarsity Press",
    "Crossway",
    "WestBow Press",
    "Ave Maria Press",
    "Ignatius Press",
    "Abingdon Press",
    "Paraclete Press",
    "Loyola Press",
    "Shambhala Publications",
    "Bethany House",
    "FaithWords",
    "Paideia Press",
    # Specialty & academic smaller
    "Beacon Press",
    "Polity Press",
    "Verso Books",
    "New Left Review",
    "Monthly Review Press",
    "Zed Books",
    "Open Humanities Press",
    "University of Michigan Press",
    "University of Toronto Press",
    "Bloomsbury Qatar Foundation Journals",
    "Brill Publishers",
    "De Gruyter",
    "I.B. Tauris",
    "Routledge India",
    "Springer Healthcare",
    "Wiley-VCH",
    "CRC Press UK",
    # Art, design, photography
    "Phaidon Press",
    "Taschen",
    "Abrams Books",
    "Thames & Hudson",
    "Rizzoli",
    "Chronicle Books",
    "Aperture",
    "Ariel Books",
    "Steidl",
    "Prestel",
    # Local & regional US indie
    "Akashic Books",
    "Arcadia Publishing",
    "Local Reads Press",
    "McSweeney's",
    "Archipelago Books",
    "Coffee House Press",  # duplicates allowed
    # Niche nonfiction / pop culture
    "MIT Press",
    "Verso",
    "New Press",
    "Beacon Press",
    "Chelsea Green Publishing",
    "Basic Books",
    "Zed Books",
    "Chelsea Green",
    "Chelsea Green Publishing",  # duplicates allowed
    # More global & academic
    "Oxford University Press India",
    "Cambridge University Press India",
    "Pearson India",
    "Wiley India",
    "Springer India",
    "Elsevier Ltd UK",
    "Palgrave Macmillan UK",
    "Routledge UK",
    "John Benjamins Publishing Company",
    "Edinburgh University Press",
    "University Press of New England",
    "SUNY Press",
    # Journalism/media publishers
    "The New Press",
    "Verso",
    "PublicAffairs",
    "Melville House",
    "Seven Stories Press",
    "OR Books",
    "Union Square & Co.",
    "One World Publications",
    "Oneworld Academic",
    "Bloomsbury Academic",
    # More independents
    "McSweeney’s",
    "Akashic Books",
    "Soft Skull Press",
    "Zero Books",
    "Reaktion Books",
    "Duke University Press",
    "Minnesota Historical Society Press",
    "New York Review Books",
    "Fitzcarraldo Editions",
    "Pushkin Press",
    "And Other Stories",
    "Weidenfeld & Nicolson",
    "Chatto & Windus",
    "Jonathan Cape",
    "Bloomsbury USA",
    "Europa Editions UK",
    "Jericho Books",
    "Transit Books",
    "Bellevue Literary Press",
    "Liveright",
    "Restless Books",
    "Scribner",
    "Free Press",
    # Regional independent EU
    "Gallimard Jeunesse",
    "Lannoo Publishers",
    "SMK Publications",
    "Holland Park Press",
    "Einaudi",
    "Feltrinelli",
    "Mondadori",
    "Roli Books",
    "Aleph Book Company",
    "Niyogi Books",
    "Tara Press",
    "Penguin India",
    "HarperCollins India",
    "Rupa Publications",
    "Shipra Publications",
    # Latin America
    "Lumen Editores",
    "Editorial Planeta Colombia",
    "Norma Editorial",
    "Santillana",
    "Editorial Universitaria",
    "Siglo XXI Editores",
    # Canada & Australia
    "House of Anansi Press",
    "ECW Press",
    "Quick Brown Fox",
    "Allen & Unwin",
    "Text Publishing",
    "Pan Macmillan Australia",
    # Eastern Europe & Asia
    "Humanitas Publishing House",
    "Korean Minjok Leadership Academy Press",
    "Znak",
    "Wydawnictwo Literackie",
    "Editura Humanitas",
    "Shanghai Translation Publishing House",
    "Beijing October Literature & Art Publishing House",
    "Shogakukan",
    "Kodansha",
    "Kadokawa",
    "Nikkei Publishing Inc",
    # Small poetry & chapbooks
    "Poets & Writers Press",
    "Off the Grid Press",
    "Three Conditions Press",
    "Finishing Line Press",
    "Sagging Meniscus Press",
    "Finishing Line Press",
    # DIY/zines/community
    "Microcosm Publishing",
    "AK Press",
    "Common Notions",
    "Left Bank Books",
    "Emerald Street Press",
    "Black & Red",
    "Seen Press",
    # Else
    "O'Reilly Media",
    "Packt Publishing",
    "Manning Publications",
    "No Starch Press",
    "Apress",
    "Wrox Press",
]
