title_list = [
    "Pride and Prejudice",
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Moby-Dick",
    "War and Peace",
    "The Catcher in the Rye",
    "The Hobbit",
    "Fahrenheit 451",
    "Jane Eyre",
    "Brave New World",
    "Crime and Punishment",
    "Wuthering Heights",
    "The Odyssey",
    "Anna Karenina",
    "The Brothers Karamazov",
    "One Hundred Years of Solitude",
    "The Lord of the Rings",
    "Animal Farm",
    "The Picture of Dorian Gray",
    "Ulysses",
    "The Grapes of Wrath",
    "Lord of the Flies",
    "Slaughterhouse-Five",
    "Catch-22",
    "Beloved",
    "The Sound and the Fury",
    "Great Expectations",
    "Alice's Adventures in Wonderland",
    "Dracula",
    "Frankenstein",
    "The Kite Runner",
    "Life of Pi",
    "The Alchemist",
    "The Chronicles of Narnia",
    "The Secret Garden",
    "A Tale of Two Cities",
    "Les Misérables",
    "The Count of Monte Cristo",
    "A Passage to India",
    "The Sun Also Rises",
    "Invisible Man",
    "Their Eyes Were Watching God",
    "Gone with the Wind",
    "Rebecca",
    "The Handmaid's Tale",
    "Middlemarch",
    "The Trial",
    "Don Quixote",
    "The Divine Comedy",
    "Madame Bovary",
    "Heart of Darkness",
    "On the Road",
    "The Bell Jar",
    "The Color Purple",
    "The Outsiders",
    "Siddhartha",
    "The Old Man and the Sea",
    "Of Mice and Men",
    "East of Eden",
    "The Road",
    "The Iliad",
    "The Stranger",
    "The Metamorphosis",
    "Atlas Shrugged",
    "Gone Girl",
    "The Girl with the Dragon Tattoo",
    "The Help",
    "Life After Life",
    "Memoirs of a Geisha",
    "Atonement",
    "The Time Traveler's Wife",
    "Cloud Atlas",
    "The Shadow of the Wind",
    "The Book Thief",
    "Water for Elephants",
    "All the Light We Cannot See",
    "The Night Circus",
    "The Goldfinch",
    "The Hunger Games",
    "The Fault in Our Stars",
    "Twilight",
    "Divergent",
    "The Maze Runner",
    "Ready Player One",
    "The Martian",
    "Ender's Game",
    "Dune",
    "Neuromancer",
    "Snow Crash",
    "Do Androids Dream of Electric Sheep?",
    "The Left Hand of Darkness",
    "A Game of Thrones",
    "The Name of the Wind",
    "Mistborn",
    "The Lies of Locke Lamora",
    "American Gods",
    "Good Omens",
    "The Stand",
    "It",
    "Carrie",
    "The Shining",
    "Pet Sematary",
    "The Haunting of Hill House",
    "Bird Box",
    "The Exorcist",
    "Dr. Jekyll and Mr. Hyde",
    "The Turn of the Screw",
    "The Woman in White",
    "Rebecca",
    "The Hound of the Baskervilles",
    "And Then There Were None",
    "Murder on the Orient Express",
    "The Maltese Falcon",
    "The Big Sleep",
    "In Cold Blood",
    "Gone Baby Gone",
    "The Girl on the Train",
    "Big Little Lies",
    "Sharp Objects",
    "The Silent Patient",
    "The Da Vinci Code",
    "Angels & Demons",
    "Inferno",
    "The Lost Symbol",
    "Digital Fortress",
    "The Secret History",
    "The Gold Coast",
    "White Teeth",
    "The Remains of the Day",
    "A Clockwork Orange",
    "Lolita",
    "Native Son",
    "Of Human Bondage",
    "To the Lighthouse",
    "Mrs Dalloway",
    "A Room of One's Own",
    "Persuasion",
    "Emma",
    "Sense and Sensibility",
    "North and South",
    "The Tenant of Wildfell Hall",
    "The Turn of the Screw",
    "The Awakening",
    "The Scarlet Letter",
    "The Adventures of Huckleberry Finn",
    "The Adventures of Tom Sawyer",
    "Treasure Island",
    "The Call of the Wild",
    "White Fang",
    "Little Women",
    "Anne of Green Gables",
    "Heidi",
    "Peter Pan",
    "The Wind in the Willows",
    "Charlotte's Web",
    "Matilda",
    "The Cat in the Hat",
    "Where the Wild Things Are",
    "Goodnight Moon",
    "The Very Hungry Caterpillar",
    "Green Eggs and Ham",
    "Oh, the Places You'll Go!",
    "The Giving Tree",
    "Corduroy",
    "The Polar Express",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows",
    "The Hunger Games",
    "Catching Fire",
    "Mockingjay",
    "The Lightning Thief",
    "The Sea of Monsters",
    "The Titan's Curse",
    "The Battle of the Labyrinth",
    "The Last Olympian",
    "The Color of Magic",
    "The Light Fantastic",
    "Equal Rites",
    "Mort",
    "Guards! Guards!",
    "Good Omens",
    "Small Gods",
    "The Eye of the World",
    "The Great Hunt",
    "The Dragon Reborn",
    "The Shadow Rising",
    "The Fires of Heaven",
    "Lord of Chaos",
    "A Crown of Swords",
    "The Path of Daggers",
    "Winter's Heart",
    "Crossroads of Twilight",
    "Knife of Dreams",
    "The Gathering Storm",
    "Oathbringer",
    "Rhythm of War",
    "The Way of Kings",
    "Words of Radiance",
    "Mistborn: The Final Empire",
    "The Well of Ascension",
    "The Hero of Ages",
    "Elantris",
    "Warbreaker",
    "The Eye of the World",
    "A Memory of Light",
    "The Riftwar Saga: Magician",
    "The Riftwar Saga: Silverthorn",
    "The Riftwar Saga: A Darkness at Sethanon",
    "The Belgariad: Pawn of Prophecy",
    "The Belgariad: Queen of Sorcery",
    "The Belgariad: Magician's Gambit",
    "The Belgariad: Castle of Wizardry",
    "The Belgariad: Enchanters' End Game",
    "The Chronicles of Amber: Nine Princes in Amber",
    "The Chronicles of Amber: The Guns of Avalon",
    "The Chronicles of Amber: Sign of the Unicorn",
    "The Chronicles of Amber: The Hand of Oberon",
    "The Chronicles of Amber: The Courts of Chaos",
    "The Chronicles of Amber: Trumps of Doom",
    "The Chronicles of Amber: Blood of Amber",
    "The Chronicles of Amber: Sign of Chaos",
    "The Chronicles of Amber: Knight of Shadows",
    "The Chronicles of Amber: Prince of Chaos",
    "The Chronicles of Amber: The Trumps of Doom",
    "The Iron Druid Chronicles: Hounded",
    "The Iron Druid Chronicles: Hexed",
    "The Iron Druid Chronicles: Hammered",
    "The Iron Druid Chronicles: Tricked",
    "The Iron Druid Chronicles: Trapped",
    "The Iron Druid Chronicles: Hunted",
    "The Dresden Files: Storm Front",
    "The Dresden Files: Fool Moon",
    "The Dresden Files: Grave Peril",
    "The Dresden Files: Summer Knight",
    "The Dresden Files: Death Masks",
    "The Dresden Files: Blood Rites",
    "The Dresden Files: Dead Beat",
    "The Dresden Files: Proven Guilty",
    "The Dresden Files: White Night",
    "The Dresden Files: Small Favor",
    "The Wheel of Time: The Eye of the World",
    "The Wheel of Time: The Great Hunt",
    "The Wheel of Time: The Dragon Reborn",
    "The Wheel of Time: The Shadow Rising",
    "The Wheel of Time: The Fires of Heaven",
    "The Wheel of Time: Lord of Chaos",
    "The Wheel of Time: A Crown of Swords",
    "The Wheel of Time: The Path of Daggers",
    "The Wheel of Time: Winter's Heart",
    "The Wheel of Time: Crossroads of Twilight",
    "The Wheel of Time: Knife of Dreams",
    "The Wheel of Time: The Gathering Storm",
    "The Wheel of Time: Towers of Midnight",
    "The Wheel of Time: A Memory of Light",
    "The Stand",
    "11/22/63",
    "Under the Dome",
    "Joyland",
    "Duma Key",
    "It",
    "The Outsider",
    "Misery",
    "The Green Mile",
    "Carrie",
    "The Shining",
    "Pet Sematary",
    "Doctor Sleep",
    "Salem’s Lot",
    "The Long Walk",
    "The Dark Tower: The Gunslinger",
    "The Dark Tower II: The Drawing of the Three",
    "The Dark Tower III: The Waste Lands",
    "The Dark Tower IV: Wizard and Glass",
    "The Dark Tower V: Wolves of the Calla",
    "The Dark Tower VI: Song of Susannah",
    "The Dark Tower VII: The Dark Tower",
    "The Institute",
    "Billy Summers",
    "Fairy Tale",
    "A Brief History of Time",
    "The Universe in a Nutshell",
    "The Grand Design",
    "Black Holes and Baby Universes",
    "Astrophysics for People in a Hurry",
    "Sapiens: A Brief History of Humankind",
    "Homo Deus",
    "21 Lessons for the 21st Century",
    "Educated",
    "Becoming",
    "The Glass Castle",
    "The Liars’ Club",
    "Wild",
    "When Breath Becomes Air",
    "The Wright Brothers",
    "Team of Rivals",
    "The Splendid and the Vile",
    "The Body Keeps the Score",
    "Thinking, Fast and Slow",
    "Outliers",
    "Blink",
    "The Tipping Point",
    "Freakonomics",
    "Quiet",
    "Guns, Germs, and Steel",
    "The Immortal Life of Henrietta Lacks",
    "Bad Blood",
    "The Devil in the White City",
    "In Cold Blood",
    "Unbroken",
    "All the President’s Men",
    "Dead Wake",
    "Unbroken",
    "The Radium Girls",
    "Hidden Figures",
    "The Wright Brothers",
    "Longitude",
    "The Man Who Mistook His Wife for a Hat",
    "Surely You're Joking, Mr. Feynman!",
    "Steve Jobs",
    "The Innovators",
    "Leonardo da Vinci",
    "Einstein: His Life and Universe",
    "Alexander Hamilton",
    "Grant",
    "Team of Rivals",
    "The Looming Tower",
    "The Rise and Fall of the Third Reich",
    "The Diary of a Young Girl",
    "Night",
    "Man’s Search for Meaning",
    "The Gulag Archipelago",
    "A People’s History of the United States",
    "The Sixth Extinction",
    "The Emperor of All Maladies",
    "Educated",
    "Born a Crime",
    "When Breath Becomes Air",
    "The Alchemist",
    "The Pilgrimage",
    "Brida",
    "Eleven Minutes",
    "The Prophet",
    "Tuesdays with Morrie",
    "The Four Agreements",
    "The Mastery of Love",
    "The Power of Now",
    "A New Earth",
    "The Seven Spiritual Laws of Success",
    "The Road Less Traveled",
    "The Book of Joy",
    "Siddhartha",
    "Zen and the Art of Motorcycle Maintenance",
    "Walden",
    "Into the Wild",
    "On the Road",
    "Fear and Loathing in Las Vegas",
    "Down and Out in Paris and London",
    "The Sun Also Rises",
    "For Whom the Bell Tolls",
    "The Old Man and the Sea",
    "Slaughterhouse-Five",
    "Cat’s Cradle",
    "Breakfast of Champions",
    "One Flew Over the Cuckoo’s Nest",
    "The Bell Jar",
    "It's Kind of a Funny Story",
    "The Perks of Being a Wallflower",
    "Looking for Alaska",
    "Thirteen Reasons Why",
    "Eleanor & Park",
    "Speak",
    "The Hunger Games Trilogy Box Set",
    "The Giver",
    "Uglies",
    "Matched",
    "His Dark Materials: The Golden Compass",
    "The Subtle Knife",
    "The Amber Spyglass",
    "The Magicians",
    "The Magician King",
    "The Lies of Locke Lamora",
    "Red Seas Under Red Skies",
    "Promise of Blood",
    "The Lies of Locke Lamora",
    "The Name of the Wind",
    "The Wise Man’s Fear",
    "The Slow Regard of Silent Things",
    "The Way of Kings",
    "Words of Radiance",
    "Oathbringer",
    "Rhythm of War",
    "The Hobbit",
    "The Fellowship of the Ring",
    "The Two Towers",
    "The Return of the King",
    "The Silmarillion",
    "Unfinished Tales",
    "A Game of Thrones",
    "A Clash of Kings",
    "A Storm of Swords",
    "A Feast for Crows",
    "A Dance with Dragons",
    "The Winds of Winter? (forthcoming)",
    "The Eye of the World",
    "The Great Hunt",
    "The Dragon Reborn",
    "The Shadow Rising",
    "The Fires of Heaven",
    "Lord of Chaos",
    "A Crown of Swords",
    "The Path of Daggers",
    "Winter’s Heart",
    "Crossroads of Twilight",
    "Knife of Dreams",
    "The Gathering Storm",
    "Towers of Midnight",
    "A Memory of Light",
    "Mistborn: The Final Empire",
    "The Well of Ascension",
    "The Hero of Ages",
    "Elantris",
    "Warbreaker",
    "The Way of Shadows",
    "Shadow’s Edge",
    "Beyond the Shadows",
    "Night Angel Trilogy Box Set",
    "The Wheel of Time Companion",
    "The World of Ice & Fire",
    "Fire & Blood",
    "The Prince of Nothing",
    "The Kingkiller Chronicle",
    # Added poetry
    "Leaves of Grass",
    "The Waste Land",
    "The Collected Poems of W. B. Yeats",
    "Ariel",
    "The Complete Poems of Emily Dickinson",
    "The Divine Comedy",
    "Paradise Lost",
    "Eugene Onegin",
    "The Love Song of J. Alfred Prufrock",
    "Howl",
    "The Raven",
    "The Sun and Her Flowers",
    "Milk and Honey",
    "Citizen: An American Lyric",
    "The Collected Poems of Langston Hughes",
    # Continue memoirs and biographies
    "Open",
    "My Life",
    "Becoming",
    "I Know Why the Caged Bird Sings",
    "Angela’s Ashes",
    "The Glass Castle",
    "Educated",
    "Born a Crime",
    "Steve Jobs",
    "Elon Musk",
    "The Wright Brothers",
    "Alexander Hamilton",
    # Continue sci-fi/fantasy
    "Do Androids Dream of Electric Sheep?",
    "Neuromancer",
    "Snow Crash",
    "Hyperion",
    "The Fall of Hyperion",
    "Ender’s Game",
    "Speaker for the Dead",
    "Dune Messiah",
    "Children of Dune",
    "God Emperor of Dune",
    "Heretics of Dune",
    "Chapterhouse: Dune",
    "Foundation",
    "Foundation and Empire",
    "Second Foundation",
    "I, Robot",
    "The Caves of Steel",
    "The Naked Sun",
    "The Robots of Dawn",
    "The Hitchhiker’s Guide to the Galaxy",
    "The Restaurant at the End of the Universe",
    "Life, the Universe and Everything",
    "So Long, and Thanks for All the Fish",
    "Mostly Harmless",
    "The Martian Chronicles",
    "Fahrenheit 451",
    "Brave New World",
    "The Forever War",
    "The Left Hand of Darkness",
    "Kindred",
    "Parable of the Sower",
    "Parable of the Talents",
]
