"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.dbu.v0.dbumodels_pb2
import ansys.api.discovery.v0.connections.contact_pb2
import ansys.api.discovery.v0.discoverymodels_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _ContactGoupConversionType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ContactGoupConversionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContactGoupConversionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SLIDING_CONTACT_GROUP: ContactGoupConversionType.ValueType = ...  # 0
    JOINT: ContactGoupConversionType.ValueType = ...  # 1
    BOND: ContactGoupConversionType.ValueType = ...  # 2
    EXCLUDE: ContactGoupConversionType.ValueType = ...  # 3
class ContactGoupConversionType(_ContactGoupConversionType, metaclass=_ContactGoupConversionTypeEnumTypeWrapper):
    """Contact group condition definitions"""
    pass

SLIDING_CONTACT_GROUP: ContactGoupConversionType.ValueType = ...  # 0
JOINT: ContactGoupConversionType.ValueType = ...  # 1
BOND: ContactGoupConversionType.ValueType = ...  # 2
EXCLUDE: ContactGoupConversionType.ValueType = ...  # 3
global___ContactGoupConversionType = ContactGoupConversionType


class ConvertContactGroupChangeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OBJECT_ID_FIELD_NUMBER: builtins.int
    CONTACT_GROUP_TYPE_FIELD_NUMBER: builtins.int
    CONTACT_PAIRS_FIELD_NUMBER: builtins.int
    IDEALIZE_FIELD_NUMBER: builtins.int
    FRICTION_COEFFICIENT_FIELD_NUMBER: builtins.int
    @property
    def object_id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    contact_group_type: global___ContactGoupConversionType.ValueType = ...
    @property
    def contact_pairs(self) -> ansys.api.discovery.v0.connections.contact_pb2.ContactPairs: ...
    idealize: builtins.bool = ...
    friction_coefficient: builtins.float = ...
    def __init__(self,
        *,
        object_id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        contact_group_type : global___ContactGoupConversionType.ValueType = ...,
        contact_pairs : typing.Optional[ansys.api.discovery.v0.connections.contact_pb2.ContactPairs] = ...,
        idealize : typing.Optional[builtins.bool] = ...,
        friction_coefficient : typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_friction_coefficient",b"_friction_coefficient","_idealize",b"_idealize","contact_pairs",b"contact_pairs","friction_coefficient",b"friction_coefficient","idealize",b"idealize","object_id",b"object_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_friction_coefficient",b"_friction_coefficient","_idealize",b"_idealize","contact_group_type",b"contact_group_type","contact_pairs",b"contact_pairs","friction_coefficient",b"friction_coefficient","idealize",b"idealize","object_id",b"object_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_friction_coefficient",b"_friction_coefficient"]) -> typing.Optional[typing_extensions.Literal["friction_coefficient"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_idealize",b"_idealize"]) -> typing.Optional[typing_extensions.Literal["idealize"]]: ...
global___ConvertContactGroupChangeRequest = ConvertContactGroupChangeRequest

class ContactGroupProperties(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONTACT_TYPE_FIELD_NUMBER: builtins.int
    CONTACT_PAIRS_FIELD_NUMBER: builtins.int
    FRICTION_COEFFICIENT_FIELD_NUMBER: builtins.int
    STIFFNESS_FACTOR_FIELD_NUMBER: builtins.int
    DETECTION_RADIUS_FACTOR_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    SHEAR_STRENGHT_FIELD_NUMBER: builtins.int
    TENSILE_STRENGTH_FIELD_NUMBER: builtins.int
    ARE_STRENGTH_LIMITS_SET_FIELD_NUMBER: builtins.int
    ADJUST_GAP_OR_OVERLAP_FIELD_NUMBER: builtins.int
    MAKE_JUST_TOUCHING_FIELD_NUMBER: builtins.int
    IDEALIZE_FIELD_NUMBER: builtins.int
    SPECIFY_THERMAL_CONDUCTANCE_FIELD_NUMBER: builtins.int
    SPECIFY_THERMAL_CONDUCTANCE_FROM_THICKNESS_AND_MATERIAL_FIELD_NUMBER: builtins.int
    SPECIFY_ELECTRIC_CONDUCTANCE_FIELD_NUMBER: builtins.int
    SPECIFY_ELECTRIC_CONDUCTANCE_FROM_THICKNESS_AND_MATERIAL_FIELD_NUMBER: builtins.int
    THERMAL_CONTACT_CONDUCTANCE_FIELD_NUMBER: builtins.int
    THERMAL_CONDUCTANCE_THICKNESS_FIELD_NUMBER: builtins.int
    ELECTRICAL_CONTACT_CONDUCTANCE_FIELD_NUMBER: builtins.int
    ELECTRICAL_CONDUCTANCE_THICKNESS_FIELD_NUMBER: builtins.int
    THERMAL_CONDUCTANCE_OPTION_FIELD_NUMBER: builtins.int
    contact_type: ansys.api.discovery.v0.connections.contact_pb2.ContactType.ValueType = ...
    @property
    def contact_pairs(self) -> ansys.api.discovery.v0.connections.contact_pb2.ContactPairs: ...
    friction_coefficient: builtins.float = ...
    stiffness_factor: builtins.float = ...
    detection_radius_factor: builtins.float = ...
    @property
    def offset(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    @property
    def shear_strenght(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    @property
    def tensile_strength(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    are_strength_limits_set: builtins.bool = ...
    adjust_gap_or_overlap: builtins.bool = ...
    make_just_touching: builtins.bool = ...
    idealize: builtins.bool = ...
    specify_thermal_conductance: builtins.bool = ...
    """OBSOLETE FROM VERSION 2026.1 ONWARDS"""

    specify_thermal_conductance_from_thickness_and_material: builtins.bool = ...
    """OBSOLETE FROM VERSION 2026.1 ONWARDS"""

    specify_electric_conductance: builtins.bool = ...
    specify_electric_conductance_from_thickness_and_material: builtins.bool = ...
    @property
    def thermal_contact_conductance(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    @property
    def thermal_conductance_thickness(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    @property
    def electrical_contact_conductance(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    @property
    def electrical_conductance_thickness(self) -> ansys.api.discovery.v0.discoverymodels_pb2.Quantity: ...
    thermal_conductance_option: ansys.api.discovery.v0.discoverymodels_pb2.ThermalConductanceOptionType.ValueType = ...
    def __init__(self,
        *,
        contact_type : ansys.api.discovery.v0.connections.contact_pb2.ContactType.ValueType = ...,
        contact_pairs : typing.Optional[ansys.api.discovery.v0.connections.contact_pb2.ContactPairs] = ...,
        friction_coefficient : builtins.float = ...,
        stiffness_factor : builtins.float = ...,
        detection_radius_factor : builtins.float = ...,
        offset : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        shear_strenght : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        tensile_strength : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        are_strength_limits_set : builtins.bool = ...,
        adjust_gap_or_overlap : builtins.bool = ...,
        make_just_touching : builtins.bool = ...,
        idealize : builtins.bool = ...,
        specify_thermal_conductance : builtins.bool = ...,
        specify_thermal_conductance_from_thickness_and_material : builtins.bool = ...,
        specify_electric_conductance : builtins.bool = ...,
        specify_electric_conductance_from_thickness_and_material : builtins.bool = ...,
        thermal_contact_conductance : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        thermal_conductance_thickness : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        electrical_contact_conductance : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        electrical_conductance_thickness : typing.Optional[ansys.api.discovery.v0.discoverymodels_pb2.Quantity] = ...,
        thermal_conductance_option : ansys.api.discovery.v0.discoverymodels_pb2.ThermalConductanceOptionType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["contact_pairs",b"contact_pairs","electrical_conductance_thickness",b"electrical_conductance_thickness","electrical_contact_conductance",b"electrical_contact_conductance","offset",b"offset","shear_strenght",b"shear_strenght","tensile_strength",b"tensile_strength","thermal_conductance_thickness",b"thermal_conductance_thickness","thermal_contact_conductance",b"thermal_contact_conductance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["adjust_gap_or_overlap",b"adjust_gap_or_overlap","are_strength_limits_set",b"are_strength_limits_set","contact_pairs",b"contact_pairs","contact_type",b"contact_type","detection_radius_factor",b"detection_radius_factor","electrical_conductance_thickness",b"electrical_conductance_thickness","electrical_contact_conductance",b"electrical_contact_conductance","friction_coefficient",b"friction_coefficient","idealize",b"idealize","make_just_touching",b"make_just_touching","offset",b"offset","shear_strenght",b"shear_strenght","specify_electric_conductance",b"specify_electric_conductance","specify_electric_conductance_from_thickness_and_material",b"specify_electric_conductance_from_thickness_and_material","specify_thermal_conductance",b"specify_thermal_conductance","specify_thermal_conductance_from_thickness_and_material",b"specify_thermal_conductance_from_thickness_and_material","stiffness_factor",b"stiffness_factor","tensile_strength",b"tensile_strength","thermal_conductance_option",b"thermal_conductance_option","thermal_conductance_thickness",b"thermal_conductance_thickness","thermal_contact_conductance",b"thermal_contact_conductance"]) -> None: ...
global___ContactGroupProperties = ContactGroupProperties

class ContactGroupDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    PARENT_ID_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    SIDE1_LOCATIONS_FIELD_NUMBER: builtins.int
    SIDE2_LOCATIONS_FIELD_NUMBER: builtins.int
    SUPPRESSED_FIELD_NUMBER: builtins.int
    CONTACT_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    @property
    def parent_id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    label: typing.Text = ...
    @property
    def side1_locations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def side2_locations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    suppressed: builtins.bool = ...
    @property
    def contact(self) -> global___ContactGroupProperties: ...
    def __init__(self,
        *,
        id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        parent_id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        label : typing.Text = ...,
        side1_locations : typing.Optional[typing.Iterable[typing.Text]] = ...,
        side2_locations : typing.Optional[typing.Iterable[typing.Text]] = ...,
        suppressed : builtins.bool = ...,
        contact : typing.Optional[global___ContactGroupProperties] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["contact",b"contact","id",b"id","parent_id",b"parent_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["contact",b"contact","id",b"id","label",b"label","parent_id",b"parent_id","side1_locations",b"side1_locations","side2_locations",b"side2_locations","suppressed",b"suppressed"]) -> None: ...
global___ContactGroupDefinition = ContactGroupDefinition
