"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.dbu.v0.dbumodels_pb2
import ansys.api.discovery.v0.discoverymodels_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _FluidInterfaceType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _FluidInterfaceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FluidInterfaceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CONDUCTING: FluidInterfaceType.ValueType = ...  # 0
    EXCLUDE: FluidInterfaceType.ValueType = ...  # 1
class FluidInterfaceType(_FluidInterfaceType, metaclass=_FluidInterfaceTypeEnumTypeWrapper):
    """Contact group condition definitions"""
    pass

CONDUCTING: FluidInterfaceType.ValueType = ...  # 0
EXCLUDE: FluidInterfaceType.ValueType = ...  # 1
global___FluidInterfaceType = FluidInterfaceType


class _FluidInterfaceFaceGroupingMethod:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _FluidInterfaceFaceGroupingMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FluidInterfaceFaceGroupingMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    GROUPBYBODY: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 0
    GROUPTANGENTFACES: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 1
    NOGROUPING: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 2
class FluidInterfaceFaceGroupingMethod(_FluidInterfaceFaceGroupingMethod, metaclass=_FluidInterfaceFaceGroupingMethodEnumTypeWrapper):
    pass

GROUPBYBODY: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 0
GROUPTANGENTFACES: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 1
NOGROUPING: FluidInterfaceFaceGroupingMethod.ValueType = ...  # 2
global___FluidInterfaceFaceGroupingMethod = FluidInterfaceFaceGroupingMethod


class _FluidInterfaceFaceThermalConductanceMethod:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _FluidInterfaceFaceThermalConductanceMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FluidInterfaceFaceThermalConductanceMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    INSULATED: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 0
    THERMALCONDUCTANCE: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 1
    THICKNESSANDCONDUCTIVITY: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 2
    THICKNESSANDMATERIAL: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 3
    CONDUCTOR: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 4
class FluidInterfaceFaceThermalConductanceMethod(_FluidInterfaceFaceThermalConductanceMethod, metaclass=_FluidInterfaceFaceThermalConductanceMethodEnumTypeWrapper):
    pass

INSULATED: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 0
THERMALCONDUCTANCE: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 1
THICKNESSANDCONDUCTIVITY: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 2
THICKNESSANDMATERIAL: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 3
CONDUCTOR: FluidInterfaceFaceThermalConductanceMethod.ValueType = ...  # 4
global___FluidInterfaceFaceThermalConductanceMethod = FluidInterfaceFaceThermalConductanceMethod


class ChangeFluidInterfaceTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OBJECT_ID_FIELD_NUMBER: builtins.int
    INTERFACE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def object_id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    interface_type: global___FluidInterfaceType.ValueType = ...
    def __init__(self,
        *,
        object_id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        interface_type : global___FluidInterfaceType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["object_id",b"object_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interface_type",b"interface_type","object_id",b"object_id"]) -> None: ...
global___ChangeFluidInterfaceTypeRequest = ChangeFluidInterfaceTypeRequest

class ChangeFluidInterfaceFaceGroupingMethodRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OBJECT_ID_FIELD_NUMBER: builtins.int
    FACE_GROUPING_METHOD_FIELD_NUMBER: builtins.int
    @property
    def object_id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    face_grouping_method: global___FluidInterfaceFaceGroupingMethod.ValueType = ...
    def __init__(self,
        *,
        object_id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        face_grouping_method : global___FluidInterfaceFaceGroupingMethod.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["object_id",b"object_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["face_grouping_method",b"face_grouping_method","object_id",b"object_id"]) -> None: ...
global___ChangeFluidInterfaceFaceGroupingMethodRequest = ChangeFluidInterfaceFaceGroupingMethodRequest

class ChangeFluidInterfaceConductanceMethodRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OBJECT_ID_FIELD_NUMBER: builtins.int
    THERMAL_CONDUCTIVITY_METHOD_FIELD_NUMBER: builtins.int
    THERMAL_CONDUCTANCE_OPTION_FIELD_NUMBER: builtins.int
    @property
    def object_id(self) -> ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier: ...
    thermal_conductivity_method: global___FluidInterfaceFaceThermalConductanceMethod.ValueType = ...
    thermal_conductance_option: ansys.api.discovery.v0.discoverymodels_pb2.ThermalConductanceOptionType.ValueType = ...
    def __init__(self,
        *,
        object_id : typing.Optional[ansys.api.dbu.v0.dbumodels_pb2.PhysicsEntityIdentifier] = ...,
        thermal_conductivity_method : global___FluidInterfaceFaceThermalConductanceMethod.ValueType = ...,
        thermal_conductance_option : ansys.api.discovery.v0.discoverymodels_pb2.ThermalConductanceOptionType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["object_id",b"object_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["object_id",b"object_id","thermal_conductance_option",b"thermal_conductance_option","thermal_conductivity_method",b"thermal_conductivity_method"]) -> None: ...
global___ChangeFluidInterfaceConductanceMethodRequest = ChangeFluidInterfaceConductanceMethodRequest
