
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-15T15:33:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "491f2152e11107273820b5f2c329b99de6854616",
 "version": "1.1.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
