# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.branch_merge_job import BranchMergeJob

class TestBranchMergeJob(unittest.TestCase):
    """BranchMergeJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BranchMergeJob:
        """Test BranchMergeJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BranchMergeJob`
        """
        model = BranchMergeJob()
        if include_optional:
            return BranchMergeJob(
                id = '',
                source = '',
                target = '',
                scheduled_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'SCHEDULED',
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                message = '',
                api_error = snowstorm_client.models.api_error.ApiError(
                    message = '', 
                    developer_message = '', 
                    additional_info = {
                        'key' : None
                        }, )
            )
        else:
            return BranchMergeJob(
        )
        """

    def testBranchMergeJob(self):
        """Test BranchMergeJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
