# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.export_configuration import ExportConfiguration

class TestExportConfiguration(unittest.TestCase):
    """ExportConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExportConfiguration:
        """Test ExportConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExportConfiguration`
        """
        model = ExportConfiguration()
        if include_optional:
            return ExportConfiguration(
                id = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                branch_path = '',
                type = 'DELTA',
                filename_effective_date = '04807288',
                concepts_and_relationships_only = True,
                unpromoted_changes_only = True,
                legacy_zip_naming = True,
                transient_effective_time = '04807288',
                start_effective_time = '04807288',
                module_ids = [
                    ''
                    ],
                refset_ids = [
                    ''
                    ],
                status = 'PENDING',
                export_file_path = '',
                start_export = True
            )
        else:
            return ExportConfiguration(
                branch_path = '',
                type = 'DELTA',
        )
        """

    def testExportConfiguration(self):
        """Test ExportConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
