# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.expression import Expression

class TestExpression(unittest.TestCase):
    """Expression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Expression:
        """Test Expression
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Expression`
        """
        model = Expression()
        if include_optional:
            return Expression(
                attributes = [
                    snowstorm_client.models.expression_attribute.ExpressionAttribute(
                        type = snowstorm_client.models.concept_micro.ConceptMicro(
                            id = '', 
                            primitive = True, 
                            term = '', ), 
                        target = snowstorm_client.models.concept_micro.ConceptMicro(
                            id = '', 
                            primitive = True, 
                            term = '', ), 
                        value = snowstorm_client.models.concrete_value.ConcreteValue(
                            data_type = 'DECIMAL', 
                            value_with_prefix = '', ), 
                        concrete = True, )
                    ],
                groups = [
                    snowstorm_client.models.expression_group.ExpressionGroup(
                        attributes = [
                            snowstorm_client.models.expression_attribute.ExpressionAttribute(
                                type = snowstorm_client.models.concept_micro.ConceptMicro(
                                    id = '', 
                                    primitive = True, 
                                    term = '', ), 
                                target = snowstorm_client.models.concept_micro.ConceptMicro(
                                    id = '', 
                                    primitive = True, 
                                    term = '', ), 
                                value = snowstorm_client.models.concrete_value.ConcreteValue(
                                    data_type = 'DECIMAL', 
                                    value_with_prefix = '', ), 
                                concrete = True, )
                            ], )
                    ],
                concepts = [
                    snowstorm_client.models.concept_micro.ConceptMicro(
                        id = '', 
                        primitive = True, 
                        term = '', )
                    ]
            )
        else:
            return Expression(
        )
        """

    def testExpression(self):
        """Test Expression"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
