# coding: utf-8

"""
    Snowstorm

    SNOMED CT Terminology Server REST API

    The version of the OpenAPI document: 10.8.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snowstorm_client.models.import_job import ImportJob

class TestImportJob(unittest.TestCase):
    """ImportJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportJob:
        """Test ImportJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportJob`
        """
        model = ImportJob()
        if include_optional:
            return ImportJob(
                status = 'WAITING_FOR_FILE',
                error_message = '',
                type = 'DELTA',
                branch_path = '',
                create_code_system_version = True,
                patch_release_version = 56,
                module_ids = [
                    ''
                    ],
                internal_release = True
            )
        else:
            return ImportJob(
        )
        """

    def testImportJob(self):
        """Test ImportJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
